// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

type Globals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (g *Globals) GetConsumerID() *string {
	if g == nil {
		return nil
	}
	return g.ConsumerID
}

func (g *Globals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}
