// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type AccountingBillCreditNotesDeleteGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (a *AccountingBillCreditNotesDeleteGlobals) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingBillCreditNotesDeleteGlobals) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

type AccountingBillCreditNotesDeleteRequest struct {
	// ID of the record you are acting upon.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
}

func (a AccountingBillCreditNotesDeleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountingBillCreditNotesDeleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountingBillCreditNotesDeleteRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AccountingBillCreditNotesDeleteRequest) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingBillCreditNotesDeleteRequest) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AccountingBillCreditNotesDeleteRequest) GetServiceID() *string {
	if a == nil {
		return nil
	}
	return a.ServiceID
}

func (a *AccountingBillCreditNotesDeleteRequest) GetRaw() *bool {
	if a == nil {
		return nil
	}
	return a.Raw
}

type AccountingBillCreditNotesDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Bill Credit Note deleted
	DeleteBillCreditNoteResponse *components.DeleteBillCreditNoteResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (a *AccountingBillCreditNotesDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AccountingBillCreditNotesDeleteResponse) GetDeleteBillCreditNoteResponse() *components.DeleteBillCreditNoteResponse {
	if a == nil {
		return nil
	}
	return a.DeleteBillCreditNoteResponse
}

func (a *AccountingBillCreditNotesDeleteResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if a == nil {
		return nil
	}
	return a.UnexpectedErrorResponse
}
