// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type AccountingDepartmentsAllGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (a *AccountingDepartmentsAllGlobals) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingDepartmentsAllGlobals) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

type AccountingDepartmentsAllRequest struct {
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// The ID of the company to scope requests to. For connectors that support multi-company, this overrides the default company configured in connection settings.
	CompanyID *string `header:"style=simple,explode=false,name=x-apideck-company-id"`
	// Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Number of results to return. Minimum 1, Maximum 200, Default 20
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded.
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// Apply filters
	Filter *components.AccountingDepartmentsFilter `queryParam:"style=deepObject,explode=true,name=filter"`
}

func (a AccountingDepartmentsAllRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountingDepartmentsAllRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountingDepartmentsAllRequest) GetRaw() *bool {
	if a == nil {
		return nil
	}
	return a.Raw
}

func (a *AccountingDepartmentsAllRequest) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingDepartmentsAllRequest) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AccountingDepartmentsAllRequest) GetServiceID() *string {
	if a == nil {
		return nil
	}
	return a.ServiceID
}

func (a *AccountingDepartmentsAllRequest) GetCompanyID() *string {
	if a == nil {
		return nil
	}
	return a.CompanyID
}

func (a *AccountingDepartmentsAllRequest) GetCursor() *string {
	if a == nil {
		return nil
	}
	return a.Cursor
}

func (a *AccountingDepartmentsAllRequest) GetLimit() *int64 {
	if a == nil {
		return nil
	}
	return a.Limit
}

func (a *AccountingDepartmentsAllRequest) GetFields() *string {
	if a == nil {
		return nil
	}
	return a.Fields
}

func (a *AccountingDepartmentsAllRequest) GetFilter() *components.AccountingDepartmentsFilter {
	if a == nil {
		return nil
	}
	return a.Filter
}

type AccountingDepartmentsAllResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Departments
	GetAccountingDepartmentsResponse *components.GetAccountingDepartmentsResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse

	Next func() (*AccountingDepartmentsAllResponse, error)
}

func (a *AccountingDepartmentsAllResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AccountingDepartmentsAllResponse) GetGetAccountingDepartmentsResponse() *components.GetAccountingDepartmentsResponse {
	if a == nil {
		return nil
	}
	return a.GetAccountingDepartmentsResponse
}

func (a *AccountingDepartmentsAllResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if a == nil {
		return nil
	}
	return a.UnexpectedErrorResponse
}
