// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type AccountingAttachmentsDeleteGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (a *AccountingAttachmentsDeleteGlobals) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingAttachmentsDeleteGlobals) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

type AccountingAttachmentsDeleteRequest struct {
	// The reference type of the document.
	ReferenceType components.AttachmentReferenceType `pathParam:"style=simple,explode=false,name=reference_type"`
	// The reference id of the object to retrieve.
	ReferenceID string `pathParam:"style=simple,explode=false,name=reference_id"`
	// ID of the record you are acting upon.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
}

func (a AccountingAttachmentsDeleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountingAttachmentsDeleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountingAttachmentsDeleteRequest) GetReferenceType() components.AttachmentReferenceType {
	if a == nil {
		return components.AttachmentReferenceType("")
	}
	return a.ReferenceType
}

func (a *AccountingAttachmentsDeleteRequest) GetReferenceID() string {
	if a == nil {
		return ""
	}
	return a.ReferenceID
}

func (a *AccountingAttachmentsDeleteRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AccountingAttachmentsDeleteRequest) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingAttachmentsDeleteRequest) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AccountingAttachmentsDeleteRequest) GetServiceID() *string {
	if a == nil {
		return nil
	}
	return a.ServiceID
}

func (a *AccountingAttachmentsDeleteRequest) GetRaw() *bool {
	if a == nil {
		return nil
	}
	return a.Raw
}

type AccountingAttachmentsDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Attachments
	DeleteAttachmentResponse *components.DeleteAttachmentResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (a *AccountingAttachmentsDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AccountingAttachmentsDeleteResponse) GetDeleteAttachmentResponse() *components.DeleteAttachmentResponse {
	if a == nil {
		return nil
	}
	return a.DeleteAttachmentResponse
}

func (a *AccountingAttachmentsDeleteResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if a == nil {
		return nil
	}
	return a.UnexpectedErrorResponse
}
