// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type AccountingBillCreditNotesOneGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (a *AccountingBillCreditNotesOneGlobals) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingBillCreditNotesOneGlobals) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

type AccountingBillCreditNotesOneRequest struct {
	// ID of the record you are acting upon.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// The ID of the company to scope requests to. For connectors that support multi-company, this overrides the default company configured in connection settings.
	CompanyID *string `header:"style=simple,explode=false,name=x-apideck-company-id"`
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded.
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
}

func (a AccountingBillCreditNotesOneRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountingBillCreditNotesOneRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountingBillCreditNotesOneRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AccountingBillCreditNotesOneRequest) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingBillCreditNotesOneRequest) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AccountingBillCreditNotesOneRequest) GetServiceID() *string {
	if a == nil {
		return nil
	}
	return a.ServiceID
}

func (a *AccountingBillCreditNotesOneRequest) GetCompanyID() *string {
	if a == nil {
		return nil
	}
	return a.CompanyID
}

func (a *AccountingBillCreditNotesOneRequest) GetRaw() *bool {
	if a == nil {
		return nil
	}
	return a.Raw
}

func (a *AccountingBillCreditNotesOneRequest) GetFields() *string {
	if a == nil {
		return nil
	}
	return a.Fields
}

type AccountingBillCreditNotesOneResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Bill Credit Note
	GetBillCreditNoteResponse *components.GetBillCreditNoteResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (a *AccountingBillCreditNotesOneResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AccountingBillCreditNotesOneResponse) GetGetBillCreditNoteResponse() *components.GetBillCreditNoteResponse {
	if a == nil {
		return nil
	}
	return a.GetBillCreditNoteResponse
}

func (a *AccountingBillCreditNotesOneResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if a == nil {
		return nil
	}
	return a.UnexpectedErrorResponse
}
