// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type AccountingExpensesAllGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (a *AccountingExpensesAllGlobals) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingExpensesAllGlobals) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

type AccountingExpensesAllRequest struct {
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// The ID of the company to scope requests to. For connectors that support multi-company, this overrides the default company configured in connection settings.
	CompanyID *string `header:"style=simple,explode=false,name=x-apideck-company-id"`
	// Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Number of results to return. Minimum 1, Maximum 200, Default 20
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// Apply filters
	Filter *components.ExpensesFilter `queryParam:"style=deepObject,explode=true,name=filter"`
}

func (a AccountingExpensesAllRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountingExpensesAllRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountingExpensesAllRequest) GetRaw() *bool {
	if a == nil {
		return nil
	}
	return a.Raw
}

func (a *AccountingExpensesAllRequest) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingExpensesAllRequest) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AccountingExpensesAllRequest) GetServiceID() *string {
	if a == nil {
		return nil
	}
	return a.ServiceID
}

func (a *AccountingExpensesAllRequest) GetCompanyID() *string {
	if a == nil {
		return nil
	}
	return a.CompanyID
}

func (a *AccountingExpensesAllRequest) GetCursor() *string {
	if a == nil {
		return nil
	}
	return a.Cursor
}

func (a *AccountingExpensesAllRequest) GetLimit() *int64 {
	if a == nil {
		return nil
	}
	return a.Limit
}

func (a *AccountingExpensesAllRequest) GetFilter() *components.ExpensesFilter {
	if a == nil {
		return nil
	}
	return a.Filter
}

type AccountingExpensesAllResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Expenses
	GetExpensesResponse *components.GetExpensesResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse

	Next func() (*AccountingExpensesAllResponse, error)
}

func (a *AccountingExpensesAllResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AccountingExpensesAllResponse) GetGetExpensesResponse() *components.GetExpensesResponse {
	if a == nil {
		return nil
	}
	return a.GetExpensesResponse
}

func (a *AccountingExpensesAllResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if a == nil {
		return nil
	}
	return a.UnexpectedErrorResponse
}
