// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type AccountingBillCreditNotesAddGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (a *AccountingBillCreditNotesAddGlobals) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingBillCreditNotesAddGlobals) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

type AccountingBillCreditNotesAddRequest struct {
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// The ID of the company to scope requests to. For connectors that support multi-company, this overrides the default company configured in connection settings.
	CompanyID      *string                        `header:"style=simple,explode=false,name=x-apideck-company-id"`
	BillCreditNote components.BillCreditNoteInput `request:"mediaType=application/json"`
}

func (a AccountingBillCreditNotesAddRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountingBillCreditNotesAddRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountingBillCreditNotesAddRequest) GetRaw() *bool {
	if a == nil {
		return nil
	}
	return a.Raw
}

func (a *AccountingBillCreditNotesAddRequest) GetConsumerID() *string {
	if a == nil {
		return nil
	}
	return a.ConsumerID
}

func (a *AccountingBillCreditNotesAddRequest) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AccountingBillCreditNotesAddRequest) GetServiceID() *string {
	if a == nil {
		return nil
	}
	return a.ServiceID
}

func (a *AccountingBillCreditNotesAddRequest) GetCompanyID() *string {
	if a == nil {
		return nil
	}
	return a.CompanyID
}

func (a *AccountingBillCreditNotesAddRequest) GetBillCreditNote() components.BillCreditNoteInput {
	if a == nil {
		return components.BillCreditNoteInput{}
	}
	return a.BillCreditNote
}

type AccountingBillCreditNotesAddResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Bill Credit Note created
	CreateBillCreditNoteResponse *components.CreateBillCreditNoteResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (a *AccountingBillCreditNotesAddResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AccountingBillCreditNotesAddResponse) GetCreateBillCreditNoteResponse() *components.CreateBillCreditNoteResponse {
	if a == nil {
		return nil
	}
	return a.CreateBillCreditNoteResponse
}

func (a *AccountingBillCreditNotesAddResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if a == nil {
		return nil
	}
	return a.UnexpectedErrorResponse
}
