// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type CrmContactsAddGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (c *CrmContactsAddGlobals) GetConsumerID() *string {
	if c == nil {
		return nil
	}
	return c.ConsumerID
}

func (c *CrmContactsAddGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CrmContactsAddRequest struct {
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string                 `header:"style=simple,explode=false,name=x-apideck-service-id"`
	Contact   components.ContactInput `request:"mediaType=application/json"`
}

func (c CrmContactsAddRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CrmContactsAddRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CrmContactsAddRequest) GetRaw() *bool {
	if c == nil {
		return nil
	}
	return c.Raw
}

func (c *CrmContactsAddRequest) GetConsumerID() *string {
	if c == nil {
		return nil
	}
	return c.ConsumerID
}

func (c *CrmContactsAddRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CrmContactsAddRequest) GetServiceID() *string {
	if c == nil {
		return nil
	}
	return c.ServiceID
}

func (c *CrmContactsAddRequest) GetContact() components.ContactInput {
	if c == nil {
		return components.ContactInput{}
	}
	return c.Contact
}

type CrmContactsAddResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Contact created
	CreateContactResponse *components.CreateContactResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (c *CrmContactsAddResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CrmContactsAddResponse) GetCreateContactResponse() *components.CreateContactResponse {
	if c == nil {
		return nil
	}
	return c.CreateContactResponse
}

func (c *CrmContactsAddResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if c == nil {
		return nil
	}
	return c.UnexpectedErrorResponse
}
