// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type CrmCustomObjectSchemasAllGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (c *CrmCustomObjectSchemasAllGlobals) GetConsumerID() *string {
	if c == nil {
		return nil
	}
	return c.ConsumerID
}

func (c *CrmCustomObjectSchemasAllGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CrmCustomObjectSchemasAllRequest struct {
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Number of results to return. Minimum 1, Maximum 200, Default 20
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// Optional unmapped key/values that will be passed through to downstream as query parameters. Ie: ?pass_through[search]=leads becomes ?search=leads
	PassThrough map[string]any `queryParam:"style=deepObject,explode=true,name=pass_through"`
}

func (c CrmCustomObjectSchemasAllRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CrmCustomObjectSchemasAllRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CrmCustomObjectSchemasAllRequest) GetRaw() *bool {
	if c == nil {
		return nil
	}
	return c.Raw
}

func (c *CrmCustomObjectSchemasAllRequest) GetConsumerID() *string {
	if c == nil {
		return nil
	}
	return c.ConsumerID
}

func (c *CrmCustomObjectSchemasAllRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CrmCustomObjectSchemasAllRequest) GetServiceID() *string {
	if c == nil {
		return nil
	}
	return c.ServiceID
}

func (c *CrmCustomObjectSchemasAllRequest) GetCursor() *string {
	if c == nil {
		return nil
	}
	return c.Cursor
}

func (c *CrmCustomObjectSchemasAllRequest) GetLimit() *int64 {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CrmCustomObjectSchemasAllRequest) GetPassThrough() map[string]any {
	if c == nil {
		return nil
	}
	return c.PassThrough
}

type CrmCustomObjectSchemasAllResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Custom object schemas
	GetCustomObjectSchemasResponse *components.GetCustomObjectSchemasResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse

	Next func() (*CrmCustomObjectSchemasAllResponse, error)
}

func (c *CrmCustomObjectSchemasAllResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CrmCustomObjectSchemasAllResponse) GetGetCustomObjectSchemasResponse() *components.GetCustomObjectSchemasResponse {
	if c == nil {
		return nil
	}
	return c.GetCustomObjectSchemasResponse
}

func (c *CrmCustomObjectSchemasAllResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if c == nil {
		return nil
	}
	return c.UnexpectedErrorResponse
}
