// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type CrmPipelinesUpdateGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (c *CrmPipelinesUpdateGlobals) GetConsumerID() *string {
	if c == nil {
		return nil
	}
	return c.ConsumerID
}

func (c *CrmPipelinesUpdateGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CrmPipelinesUpdateRequest struct {
	// ID of the record you are acting upon.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// Include raw response. Mostly used for debugging purposes
	Raw      *bool                    `default:"false" queryParam:"style=form,explode=true,name=raw"`
	Pipeline components.PipelineInput `request:"mediaType=application/json"`
}

func (c CrmPipelinesUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CrmPipelinesUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CrmPipelinesUpdateRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CrmPipelinesUpdateRequest) GetConsumerID() *string {
	if c == nil {
		return nil
	}
	return c.ConsumerID
}

func (c *CrmPipelinesUpdateRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CrmPipelinesUpdateRequest) GetServiceID() *string {
	if c == nil {
		return nil
	}
	return c.ServiceID
}

func (c *CrmPipelinesUpdateRequest) GetRaw() *bool {
	if c == nil {
		return nil
	}
	return c.Raw
}

func (c *CrmPipelinesUpdateRequest) GetPipeline() components.PipelineInput {
	if c == nil {
		return components.PipelineInput{}
	}
	return c.Pipeline
}

type CrmPipelinesUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Pipeline updated
	UpdatePipelineResponse *components.UpdatePipelineResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (c *CrmPipelinesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CrmPipelinesUpdateResponse) GetUpdatePipelineResponse() *components.UpdatePipelineResponse {
	if c == nil {
		return nil
	}
	return c.UpdatePipelineResponse
}

func (c *CrmPipelinesUpdateResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if c == nil {
		return nil
	}
	return c.UnexpectedErrorResponse
}
