// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type FileStorageDrivesAddGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (f *FileStorageDrivesAddGlobals) GetConsumerID() *string {
	if f == nil {
		return nil
	}
	return f.ConsumerID
}

func (f *FileStorageDrivesAddGlobals) GetAppID() *string {
	if f == nil {
		return nil
	}
	return f.AppID
}

type FileStorageDrivesAddRequest struct {
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string               `header:"style=simple,explode=false,name=x-apideck-service-id"`
	Drive     components.DriveInput `request:"mediaType=application/json"`
}

func (f FileStorageDrivesAddRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileStorageDrivesAddRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileStorageDrivesAddRequest) GetRaw() *bool {
	if f == nil {
		return nil
	}
	return f.Raw
}

func (f *FileStorageDrivesAddRequest) GetConsumerID() *string {
	if f == nil {
		return nil
	}
	return f.ConsumerID
}

func (f *FileStorageDrivesAddRequest) GetAppID() *string {
	if f == nil {
		return nil
	}
	return f.AppID
}

func (f *FileStorageDrivesAddRequest) GetServiceID() *string {
	if f == nil {
		return nil
	}
	return f.ServiceID
}

func (f *FileStorageDrivesAddRequest) GetDrive() components.DriveInput {
	if f == nil {
		return components.DriveInput{}
	}
	return f.Drive
}

type FileStorageDrivesAddResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Drives
	CreateDriveResponse *components.CreateDriveResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (f *FileStorageDrivesAddResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FileStorageDrivesAddResponse) GetCreateDriveResponse() *components.CreateDriveResponse {
	if f == nil {
		return nil
	}
	return f.CreateDriveResponse
}

func (f *FileStorageDrivesAddResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if f == nil {
		return nil
	}
	return f.UnexpectedErrorResponse
}
