// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type FileStorageFilesAllGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (f *FileStorageFilesAllGlobals) GetConsumerID() *string {
	if f == nil {
		return nil
	}
	return f.ConsumerID
}

func (f *FileStorageFilesAllGlobals) GetAppID() *string {
	if f == nil {
		return nil
	}
	return f.AppID
}

type FileStorageFilesAllRequest struct {
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Number of results to return. Minimum 1, Maximum 200, Default 20
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// Apply filters
	Filter *components.FilesFilter `queryParam:"style=deepObject,explode=true,name=filter"`
	// Apply sorting
	Sort *components.FilesSort `queryParam:"style=deepObject,explode=true,name=sort"`
	// Optional unmapped key/values that will be passed through to downstream as query parameters. Ie: ?pass_through[search]=leads becomes ?search=leads
	PassThrough map[string]any `queryParam:"style=deepObject,explode=true,name=pass_through"`
	// The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded.
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
}

func (f FileStorageFilesAllRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileStorageFilesAllRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileStorageFilesAllRequest) GetRaw() *bool {
	if f == nil {
		return nil
	}
	return f.Raw
}

func (f *FileStorageFilesAllRequest) GetConsumerID() *string {
	if f == nil {
		return nil
	}
	return f.ConsumerID
}

func (f *FileStorageFilesAllRequest) GetAppID() *string {
	if f == nil {
		return nil
	}
	return f.AppID
}

func (f *FileStorageFilesAllRequest) GetServiceID() *string {
	if f == nil {
		return nil
	}
	return f.ServiceID
}

func (f *FileStorageFilesAllRequest) GetCursor() *string {
	if f == nil {
		return nil
	}
	return f.Cursor
}

func (f *FileStorageFilesAllRequest) GetLimit() *int64 {
	if f == nil {
		return nil
	}
	return f.Limit
}

func (f *FileStorageFilesAllRequest) GetFilter() *components.FilesFilter {
	if f == nil {
		return nil
	}
	return f.Filter
}

func (f *FileStorageFilesAllRequest) GetSort() *components.FilesSort {
	if f == nil {
		return nil
	}
	return f.Sort
}

func (f *FileStorageFilesAllRequest) GetPassThrough() map[string]any {
	if f == nil {
		return nil
	}
	return f.PassThrough
}

func (f *FileStorageFilesAllRequest) GetFields() *string {
	if f == nil {
		return nil
	}
	return f.Fields
}

type FileStorageFilesAllResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Files
	GetFilesResponse *components.GetFilesResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse

	Next func() (*FileStorageFilesAllResponse, error)
}

func (f *FileStorageFilesAllResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FileStorageFilesAllResponse) GetGetFilesResponse() *components.GetFilesResponse {
	if f == nil {
		return nil
	}
	return f.GetFilesResponse
}

func (f *FileStorageFilesAllResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if f == nil {
		return nil
	}
	return f.UnexpectedErrorResponse
}
