// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type HrisTimeOffRequestsAddGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (h *HrisTimeOffRequestsAddGlobals) GetConsumerID() *string {
	if h == nil {
		return nil
	}
	return h.ConsumerID
}

func (h *HrisTimeOffRequestsAddGlobals) GetAppID() *string {
	if h == nil {
		return nil
	}
	return h.AppID
}

type HrisTimeOffRequestsAddRequest struct {
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID      *string                        `header:"style=simple,explode=false,name=x-apideck-service-id"`
	TimeOffRequest components.TimeOffRequestInput `request:"mediaType=application/json"`
}

func (h HrisTimeOffRequestsAddRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HrisTimeOffRequestsAddRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, []string{"TimeOffRequest"}); err != nil {
		return err
	}
	return nil
}

func (h *HrisTimeOffRequestsAddRequest) GetRaw() *bool {
	if h == nil {
		return nil
	}
	return h.Raw
}

func (h *HrisTimeOffRequestsAddRequest) GetConsumerID() *string {
	if h == nil {
		return nil
	}
	return h.ConsumerID
}

func (h *HrisTimeOffRequestsAddRequest) GetAppID() *string {
	if h == nil {
		return nil
	}
	return h.AppID
}

func (h *HrisTimeOffRequestsAddRequest) GetServiceID() *string {
	if h == nil {
		return nil
	}
	return h.ServiceID
}

func (h *HrisTimeOffRequestsAddRequest) GetTimeOffRequest() components.TimeOffRequestInput {
	if h == nil {
		return components.TimeOffRequestInput{}
	}
	return h.TimeOffRequest
}

type HrisTimeOffRequestsAddResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// TimeOffRequests
	CreateTimeOffRequestResponse *components.CreateTimeOffRequestResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (h *HrisTimeOffRequestsAddResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HrisTimeOffRequestsAddResponse) GetCreateTimeOffRequestResponse() *components.CreateTimeOffRequestResponse {
	if h == nil {
		return nil
	}
	return h.CreateTimeOffRequestResponse
}

func (h *HrisTimeOffRequestsAddResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if h == nil {
		return nil
	}
	return h.UnexpectedErrorResponse
}
