// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/models/components"
)

type IssueTrackingCollectionTicketsAddGlobals struct {
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (i *IssueTrackingCollectionTicketsAddGlobals) GetConsumerID() *string {
	if i == nil {
		return nil
	}
	return i.ConsumerID
}

func (i *IssueTrackingCollectionTicketsAddGlobals) GetAppID() *string {
	if i == nil {
		return nil
	}
	return i.AppID
}

type IssueTrackingCollectionTicketsAddRequest struct {
	// Include raw response. Mostly used for debugging purposes
	Raw *bool `default:"false" queryParam:"style=form,explode=true,name=raw"`
	// ID of the consumer which you want to get or push data from
	ConsumerID *string `header:"style=simple,explode=false,name=x-apideck-consumer-id"`
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
	ServiceID *string `header:"style=simple,explode=false,name=x-apideck-service-id"`
	// The collection ID
	CollectionID string                 `pathParam:"style=simple,explode=false,name=collection_id"`
	Ticket       components.TicketInput `request:"mediaType=application/json"`
}

func (i IssueTrackingCollectionTicketsAddRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IssueTrackingCollectionTicketsAddRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IssueTrackingCollectionTicketsAddRequest) GetRaw() *bool {
	if i == nil {
		return nil
	}
	return i.Raw
}

func (i *IssueTrackingCollectionTicketsAddRequest) GetConsumerID() *string {
	if i == nil {
		return nil
	}
	return i.ConsumerID
}

func (i *IssueTrackingCollectionTicketsAddRequest) GetAppID() *string {
	if i == nil {
		return nil
	}
	return i.AppID
}

func (i *IssueTrackingCollectionTicketsAddRequest) GetServiceID() *string {
	if i == nil {
		return nil
	}
	return i.ServiceID
}

func (i *IssueTrackingCollectionTicketsAddRequest) GetCollectionID() string {
	if i == nil {
		return ""
	}
	return i.CollectionID
}

func (i *IssueTrackingCollectionTicketsAddRequest) GetTicket() components.TicketInput {
	if i == nil {
		return components.TicketInput{}
	}
	return i.Ticket
}

type IssueTrackingCollectionTicketsAddResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Create a Ticket
	CreateTicketResponse *components.CreateTicketResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (i *IssueTrackingCollectionTicketsAddResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IssueTrackingCollectionTicketsAddResponse) GetCreateTicketResponse() *components.CreateTicketResponse {
	if i == nil {
		return nil
	}
	return i.CreateTicketResponse
}

func (i *IssueTrackingCollectionTicketsAddResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if i == nil {
		return nil
	}
	return i.UnexpectedErrorResponse
}
