// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/apideck-libraries/sdk-go/models/components"
)

type VaultConsumersDeleteGlobals struct {
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
}

func (v *VaultConsumersDeleteGlobals) GetAppID() *string {
	if v == nil {
		return nil
	}
	return v.AppID
}

type VaultConsumersDeleteRequest struct {
	// The ID of your Unify application
	AppID *string `header:"style=simple,explode=false,name=x-apideck-app-id"`
	// ID of the consumer to return
	ConsumerID string `pathParam:"style=simple,explode=false,name=consumer_id"`
}

func (v *VaultConsumersDeleteRequest) GetAppID() *string {
	if v == nil {
		return nil
	}
	return v.AppID
}

func (v *VaultConsumersDeleteRequest) GetConsumerID() string {
	if v == nil {
		return ""
	}
	return v.ConsumerID
}

type VaultConsumersDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Consumer deleted
	DeleteConsumerResponse *components.DeleteConsumerResponse
	// Unexpected error
	UnexpectedErrorResponse *components.UnexpectedErrorResponse
}

func (v *VaultConsumersDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VaultConsumersDeleteResponse) GetDeleteConsumerResponse() *components.DeleteConsumerResponse {
	if v == nil {
		return nil
	}
	return v.DeleteConsumerResponse
}

func (v *VaultConsumersDeleteResponse) GetUnexpectedErrorResponse() *components.UnexpectedErrorResponse {
	if v == nil {
		return nil
	}
	return v.UnexpectedErrorResponse
}
