// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type ActivitiesFilter struct {
	// Company ID to filter on
	CompanyID *string `queryParam:"name=company_id"`
	// Owner ID to filter on
	OwnerID *string `queryParam:"name=owner_id"`
	// Primary contact ID to filter on
	ContactID    *string    `queryParam:"name=contact_id"`
	UpdatedSince *time.Time `queryParam:"name=updated_since"`
	// Type to filter on
	Type *string `queryParam:"name=type"`
}

func (a ActivitiesFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActivitiesFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ActivitiesFilter) GetCompanyID() *string {
	if a == nil {
		return nil
	}
	return a.CompanyID
}

func (a *ActivitiesFilter) GetOwnerID() *string {
	if a == nil {
		return nil
	}
	return a.OwnerID
}

func (a *ActivitiesFilter) GetContactID() *string {
	if a == nil {
		return nil
	}
	return a.ContactID
}

func (a *ActivitiesFilter) GetUpdatedSince() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedSince
}

func (a *ActivitiesFilter) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}
