// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ApisFilter struct {
	// Status of the API. APIs with status live or beta are callable.
	Status *APIStatus `queryParam:"name=status"`
}

func (a *ApisFilter) GetStatus() *APIStatus {
	if a == nil {
		return nil
	}
	return a.Status
}
