// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type Attachment struct {
	// A unique identifier for an object.
	ID *string `json:"id,omitempty"`
	// The display id of the file
	DisplayID *string `json:"display_id,omitempty"`
	// The name of the file
	Name *string `json:"name,omitempty"`
	// The MIME type of the file.
	MimeType *string `json:"mime_type,omitempty"`
	// The size of the file in bytes
	Size      *int64               `json:"size,omitempty"`
	Reference *AttachmentReference `json:"reference,omitempty"`
	// Optional description of the file
	Description *string `json:"description,omitempty"`
	// The folder id where this attachment belong to
	ParentFolderID *string `json:"parent_folder_id,omitempty"`
	// The user who last updated the object.
	UpdatedBy *string `json:"updated_by,omitempty"`
	// The user who created the object.
	CreatedBy *string `json:"created_by,omitempty"`
	// The date and time when the object was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// The date and time when the object was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
}

func (a Attachment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Attachment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Attachment) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *Attachment) GetDisplayID() *string {
	if a == nil {
		return nil
	}
	return a.DisplayID
}

func (a *Attachment) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *Attachment) GetMimeType() *string {
	if a == nil {
		return nil
	}
	return a.MimeType
}

func (a *Attachment) GetSize() *int64 {
	if a == nil {
		return nil
	}
	return a.Size
}

func (a *Attachment) GetReference() *AttachmentReference {
	if a == nil {
		return nil
	}
	return a.Reference
}

func (a *Attachment) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *Attachment) GetParentFolderID() *string {
	if a == nil {
		return nil
	}
	return a.ParentFolderID
}

func (a *Attachment) GetUpdatedBy() *string {
	if a == nil {
		return nil
	}
	return a.UpdatedBy
}

func (a *Attachment) GetCreatedBy() *string {
	if a == nil {
		return nil
	}
	return a.CreatedBy
}

func (a *Attachment) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *Attachment) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *Attachment) GetPassThrough() []PassThroughBody {
	if a == nil {
		return nil
	}
	return a.PassThrough
}
