// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AttachmentReferenceType string

const (
	AttachmentReferenceTypeInvoice        AttachmentReferenceType = "invoice"
	AttachmentReferenceTypeBill           AttachmentReferenceType = "bill"
	AttachmentReferenceTypeBillCreditNote AttachmentReferenceType = "bill-credit-note"
	AttachmentReferenceTypeExpense        AttachmentReferenceType = "expense"
	AttachmentReferenceTypeExpenseReport  AttachmentReferenceType = "expense-report"
	AttachmentReferenceTypeQuote          AttachmentReferenceType = "quote"
)

func (e AttachmentReferenceType) ToPointer() *AttachmentReferenceType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AttachmentReferenceType) IsExact() bool {
	if e != nil {
		switch *e {
		case "invoice", "bill", "bill-credit-note", "expense", "expense-report", "quote":
			return true
		}
	}
	return false
}
