// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BatchSupportMode - The connector's overall batch capability: `none` when no resource supports a batch write, otherwise the mode most of its resources use. This is a summary — read `resources` for the answer that applies to the resource you are calling, because a connector can be `native` for one resource and `loop` for another.
type BatchSupportMode string

const (
	BatchSupportModeNone   BatchSupportMode = "none"
	BatchSupportModeNative BatchSupportMode = "native"
	BatchSupportModeLoop   BatchSupportMode = "loop"
)

func (e BatchSupportMode) ToPointer() *BatchSupportMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BatchSupportMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "native", "loop":
			return true
		}
	}
	return false
}

// BatchSupportResourcesMode - `none` means this resource refuses batch writes. `native` satisfies a batch in a single downstream call against the provider's own batch endpoint, so the request counts as one request against your plan. `loop` satisfies it as a bounded sequential fan-out, one downstream call per item — so a request of N records takes roughly N times as long and counts as N requests.
type BatchSupportResourcesMode string

const (
	BatchSupportResourcesModeNone   BatchSupportResourcesMode = "none"
	BatchSupportResourcesModeNative BatchSupportResourcesMode = "native"
	BatchSupportResourcesModeLoop   BatchSupportResourcesMode = "loop"
)

func (e BatchSupportResourcesMode) ToPointer() *BatchSupportResourcesMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BatchSupportResourcesMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "native", "loop":
			return true
		}
	}
	return false
}

type Resources struct {
	// `none` means this resource refuses batch writes. `native` satisfies a batch in a single downstream call against the provider's own batch endpoint, so the request counts as one request against your plan. `loop` satisfies it as a bounded sequential fan-out, one downstream call per item — so a request of N records takes roughly N times as long and counts as N requests.
	Mode BatchSupportResourcesMode `json:"mode"`
	// The maximum number of items this resource accepts in one request. A request carrying more is rejected before any record is written. Resources on the same connector can differ: a resource that writes records one at a time is usually capped lower than one that writes them in a single call. Absent when the connector has not declared one, in which case the platform default applies.
	MaxItems *int64 `json:"max_items,omitempty"`
}

func (r *Resources) GetMode() BatchSupportResourcesMode {
	if r == nil {
		return BatchSupportResourcesMode("")
	}
	return r.Mode
}

func (r *Resources) GetMaxItems() *int64 {
	if r == nil {
		return nil
	}
	return r.MaxItems
}

// BatchSupport - How this connector satisfies a batch write, per resource. Read this before calling a batch endpoint: support, execution mode and the per-request limit all vary by resource on the same connector, and the mode determines both latency and how many requests the call counts against your plan.
type BatchSupport struct {
	// The connector's overall batch capability: `none` when no resource supports a batch write, otherwise the mode most of its resources use. This is a summary — read `resources` for the answer that applies to the resource you are calling, because a connector can be `native` for one resource and `loop` for another.
	Mode BatchSupportMode `json:"mode"`
	// Batch support for each resource that has a batch endpoint, keyed by the batch resource name (for example `invoices-batch`). A resource absent from this map, or reporting `none`, will refuse a batch request with a 501.
	Resources map[string]Resources `json:"resources,omitempty"`
}

func (b *BatchSupport) GetMode() BatchSupportMode {
	if b == nil {
		return BatchSupportMode("")
	}
	return b.Mode
}

func (b *BatchSupport) GetResources() map[string]Resources {
	if b == nil {
		return nil
	}
	return b.Resources
}
