// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
)

// BillCreditNotesSortBy - The field on which to sort the Bill Credit Notes
type BillCreditNotesSortBy string

const (
	BillCreditNotesSortByCreatedAt BillCreditNotesSortBy = "created_at"
	BillCreditNotesSortByUpdatedAt BillCreditNotesSortBy = "updated_at"
	BillCreditNotesSortByID        BillCreditNotesSortBy = "id"
)

func (e BillCreditNotesSortBy) ToPointer() *BillCreditNotesSortBy {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BillCreditNotesSortBy) IsExact() bool {
	if e != nil {
		switch *e {
		case "created_at", "updated_at", "id":
			return true
		}
	}
	return false
}

type BillCreditNotesSort struct {
	// The field on which to sort the Bill Credit Notes
	By *BillCreditNotesSortBy `queryParam:"name=by"`
	// The direction in which to sort the results
	Direction *SortDirection `default:"asc" queryParam:"name=direction"`
}

func (b BillCreditNotesSort) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillCreditNotesSort) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BillCreditNotesSort) GetBy() *BillCreditNotesSortBy {
	if b == nil {
		return nil
	}
	return b.By
}

func (b *BillCreditNotesSort) GetDirection() *SortDirection {
	if b == nil {
		return nil
	}
	return b.Direction
}
