// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/types"
	"time"
)

// CompanyStatus - Based on the status some functionality is enabled or disabled.
type CompanyStatus string

const (
	CompanyStatusActive   CompanyStatus = "active"
	CompanyStatusInactive CompanyStatus = "inactive"
)

func (e CompanyStatus) ToPointer() *CompanyStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CompanyStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "inactive":
			return true
		}
	}
	return false
}

// TheStartMonthOfFiscalYear - The start month of fiscal year.
type TheStartMonthOfFiscalYear string

const (
	TheStartMonthOfFiscalYearJanuary   TheStartMonthOfFiscalYear = "January"
	TheStartMonthOfFiscalYearFebruary  TheStartMonthOfFiscalYear = "February"
	TheStartMonthOfFiscalYearMarch     TheStartMonthOfFiscalYear = "March"
	TheStartMonthOfFiscalYearApril     TheStartMonthOfFiscalYear = "April"
	TheStartMonthOfFiscalYearMay       TheStartMonthOfFiscalYear = "May"
	TheStartMonthOfFiscalYearJune      TheStartMonthOfFiscalYear = "June"
	TheStartMonthOfFiscalYearJuly      TheStartMonthOfFiscalYear = "July"
	TheStartMonthOfFiscalYearAugust    TheStartMonthOfFiscalYear = "August"
	TheStartMonthOfFiscalYearSeptember TheStartMonthOfFiscalYear = "September"
	TheStartMonthOfFiscalYearOctober   TheStartMonthOfFiscalYear = "October"
	TheStartMonthOfFiscalYearNovember  TheStartMonthOfFiscalYear = "November"
	TheStartMonthOfFiscalYearDecember  TheStartMonthOfFiscalYear = "December"
)

func (e TheStartMonthOfFiscalYear) ToPointer() *TheStartMonthOfFiscalYear {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TheStartMonthOfFiscalYear) IsExact() bool {
	if e != nil {
		switch *e {
		case "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December":
			return true
		}
	}
	return false
}

// TrackingCategoriesMode - The mode of tracking categories for the company on transactions
type TrackingCategoriesMode string

const (
	TrackingCategoriesModeTransaction TrackingCategoriesMode = "transaction"
	TrackingCategoriesModeLine        TrackingCategoriesMode = "line"
	TrackingCategoriesModeBoth        TrackingCategoriesMode = "both"
	TrackingCategoriesModeDisabled    TrackingCategoriesMode = "disabled"
)

func (e TrackingCategoriesMode) ToPointer() *TrackingCategoriesMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TrackingCategoriesMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "transaction", "line", "both", "disabled":
			return true
		}
	}
	return false
}

type CompanyInfo struct {
	// A unique identifier for an object.
	ID *string `json:"id,omitempty"`
	// The name of the company.
	CompanyName *string `json:"company_name,omitempty"`
	// Based on the status some functionality is enabled or disabled.
	Status *CompanyStatus `json:"status,omitempty"`
	// The legal name of the company
	LegalName *string `json:"legal_name,omitempty"`
	// country code according to ISO 3166-1 alpha-2.
	Country        *string `json:"country,omitempty"`
	SalesTaxNumber *string `json:"sales_tax_number,omitempty"`
	// Whether sales tax is calculated automatically for the company
	AutomatedSalesTax *bool `json:"automated_sales_tax,omitempty"`
	// Whether sales tax is enabled for the company
	SalesTaxEnabled *bool    `json:"sales_tax_enabled,omitempty"`
	DefaultSalesTax *TaxRate `json:"default_sales_tax,omitempty"`
	// Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
	Currency *Currency `json:"currency,omitempty"`
	// language code according to ISO 639-1. For the United States - EN
	Language *string `json:"language,omitempty"`
	// The start month of fiscal year.
	FiscalYearStartMonth *TheStartMonthOfFiscalYear `json:"fiscal_year_start_month,omitempty"`
	// Date when company file was created
	CompanyStartDate *types.Date   `json:"company_start_date,omitempty"`
	Addresses        []Address     `json:"addresses,omitempty"`
	PhoneNumbers     []PhoneNumber `json:"phone_numbers,omitempty"`
	Emails           []Email       `json:"emails,omitempty"`
	// When custom mappings are configured on the resource, the result is included here.
	CustomMappings map[string]any `json:"custom_mappings,omitempty"`
	// Whether tracking categories are enabled for the company on transactions
	TrackingCategoriesEnabled *bool `json:"tracking_categories_enabled,omitempty"`
	// The mode of tracking categories for the company on transactions
	TrackingCategoriesMode *TrackingCategoriesMode `json:"tracking_categories_mode,omitempty"`
	// A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.
	RowVersion *string `json:"row_version,omitempty"`
	// The user who last updated the object.
	UpdatedBy *string `json:"updated_by,omitempty"`
	// The user who created the object.
	CreatedBy *string `json:"created_by,omitempty"`
	// The date and time when the object was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// The date and time when the object was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

func (c CompanyInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CompanyInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CompanyInfo) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CompanyInfo) GetCompanyName() *string {
	if c == nil {
		return nil
	}
	return c.CompanyName
}

func (c *CompanyInfo) GetStatus() *CompanyStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CompanyInfo) GetLegalName() *string {
	if c == nil {
		return nil
	}
	return c.LegalName
}

func (c *CompanyInfo) GetCountry() *string {
	if c == nil {
		return nil
	}
	return c.Country
}

func (c *CompanyInfo) GetSalesTaxNumber() *string {
	if c == nil {
		return nil
	}
	return c.SalesTaxNumber
}

func (c *CompanyInfo) GetAutomatedSalesTax() *bool {
	if c == nil {
		return nil
	}
	return c.AutomatedSalesTax
}

func (c *CompanyInfo) GetSalesTaxEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.SalesTaxEnabled
}

func (c *CompanyInfo) GetDefaultSalesTax() *TaxRate {
	if c == nil {
		return nil
	}
	return c.DefaultSalesTax
}

func (c *CompanyInfo) GetCurrency() *Currency {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CompanyInfo) GetLanguage() *string {
	if c == nil {
		return nil
	}
	return c.Language
}

func (c *CompanyInfo) GetFiscalYearStartMonth() *TheStartMonthOfFiscalYear {
	if c == nil {
		return nil
	}
	return c.FiscalYearStartMonth
}

func (c *CompanyInfo) GetCompanyStartDate() *types.Date {
	if c == nil {
		return nil
	}
	return c.CompanyStartDate
}

func (c *CompanyInfo) GetAddresses() []Address {
	if c == nil {
		return nil
	}
	return c.Addresses
}

func (c *CompanyInfo) GetPhoneNumbers() []PhoneNumber {
	if c == nil {
		return nil
	}
	return c.PhoneNumbers
}

func (c *CompanyInfo) GetEmails() []Email {
	if c == nil {
		return nil
	}
	return c.Emails
}

func (c *CompanyInfo) GetCustomMappings() map[string]any {
	if c == nil {
		return nil
	}
	return c.CustomMappings
}

func (c *CompanyInfo) GetTrackingCategoriesEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.TrackingCategoriesEnabled
}

func (c *CompanyInfo) GetTrackingCategoriesMode() *TrackingCategoriesMode {
	if c == nil {
		return nil
	}
	return c.TrackingCategoriesMode
}

func (c *CompanyInfo) GetRowVersion() *string {
	if c == nil {
		return nil
	}
	return c.RowVersion
}

func (c *CompanyInfo) GetUpdatedBy() *string {
	if c == nil {
		return nil
	}
	return c.UpdatedBy
}

func (c *CompanyInfo) GetCreatedBy() *string {
	if c == nil {
		return nil
	}
	return c.CreatedBy
}

func (c *CompanyInfo) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CompanyInfo) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}
