// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EventSource - Unify event source
type EventSource string

const (
	EventSourceNative  EventSource = "native"
	EventSourceVirtual EventSource = "virtual"
)

func (e EventSource) ToPointer() *EventSource {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EventSource) IsExact() bool {
	if e != nil {
		switch *e {
		case "native", "virtual":
			return true
		}
	}
	return false
}

// ConnectorEvent - Unify event that is supported on the connector. Events are delivered via Webhooks.
type ConnectorEvent struct {
	// Unify event type
	EventType *string `json:"event_type,omitempty"`
	// Unify event source
	EventSource *EventSource `json:"event_source,omitempty"`
	// Downstream event type
	DownstreamEventType *string  `json:"downstream_event_type,omitempty"`
	Resources           []string `json:"resources,omitempty"`
	// Unify entity type
	EntityType *string `json:"entity_type,omitempty"`
}

func (c *ConnectorEvent) GetEventType() *string {
	if c == nil {
		return nil
	}
	return c.EventType
}

func (c *ConnectorEvent) GetEventSource() *EventSource {
	if c == nil {
		return nil
	}
	return c.EventSource
}

func (c *ConnectorEvent) GetDownstreamEventType() *string {
	if c == nil {
		return nil
	}
	return c.DownstreamEventType
}

func (c *ConnectorEvent) GetResources() []string {
	if c == nil {
		return nil
	}
	return c.Resources
}

func (c *ConnectorEvent) GetEntityType() *string {
	if c == nil {
		return nil
	}
	return c.EntityType
}
