// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ConnectorStatus - Status of the connector. Connectors with status live or beta are callable.
type ConnectorStatus string

const (
	ConnectorStatusLive        ConnectorStatus = "live"
	ConnectorStatusBeta        ConnectorStatus = "beta"
	ConnectorStatusEarlyAccess ConnectorStatus = "early-access"
	ConnectorStatusDevelopment ConnectorStatus = "development"
	ConnectorStatusConsidering ConnectorStatus = "considering"
)

func (e ConnectorStatus) ToPointer() *ConnectorStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ConnectorStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "live", "beta", "early-access", "development", "considering":
			return true
		}
	}
	return false
}
