// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ConnectionState - [Connection state flow](#section/Connection-state)
type ConnectionState string

const (
	ConnectionStateAvailable  ConnectionState = "available"
	ConnectionStateCallable   ConnectionState = "callable"
	ConnectionStateAdded      ConnectionState = "added"
	ConnectionStateAuthorized ConnectionState = "authorized"
	ConnectionStateInvalid    ConnectionState = "invalid"
)

func (e ConnectionState) ToPointer() *ConnectionState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ConnectionState) IsExact() bool {
	if e != nil {
		switch *e {
		case "available", "callable", "added", "authorized", "invalid":
			return true
		}
	}
	return false
}
