// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreateQuoteResponse - Quotes
type CreateQuoteResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string `json:"operation"`
	// A object containing a unique identifier for the resource that was created, updated, or deleted.
	Data UnifiedID `json:"data"`
}

func (c *CreateQuoteResponse) GetStatusCode() int64 {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateQuoteResponse) GetStatus() string {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateQuoteResponse) GetService() string {
	if c == nil {
		return ""
	}
	return c.Service
}

func (c *CreateQuoteResponse) GetResource() string {
	if c == nil {
		return ""
	}
	return c.Resource
}

func (c *CreateQuoteResponse) GetOperation() string {
	if c == nil {
		return ""
	}
	return c.Operation
}

func (c *CreateQuoteResponse) GetData() UnifiedID {
	if c == nil {
		return UnifiedID{}
	}
	return c.Data
}
