// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreateMessageResponse - Messages
type CreateMessageResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string `json:"operation"`
	// A object containing a unique identifier for the resource that was created, updated, or deleted.
	Data UnifiedID `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (c *CreateMessageResponse) GetStatusCode() int64 {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateMessageResponse) GetStatus() string {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateMessageResponse) GetService() string {
	if c == nil {
		return ""
	}
	return c.Service
}

func (c *CreateMessageResponse) GetResource() string {
	if c == nil {
		return ""
	}
	return c.Resource
}

func (c *CreateMessageResponse) GetOperation() string {
	if c == nil {
		return ""
	}
	return c.Operation
}

func (c *CreateMessageResponse) GetData() UnifiedID {
	if c == nil {
		return UnifiedID{}
	}
	return c.Data
}

func (c *CreateMessageResponse) GetRaw() map[string]any {
	if c == nil {
		return nil
	}
	return c.Raw
}
