// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
)

// CreditNotesSortBy - The field on which to sort the Customers
type CreditNotesSortBy string

const (
	CreditNotesSortByCreatedAt CreditNotesSortBy = "created_at"
	CreditNotesSortByUpdatedAt CreditNotesSortBy = "updated_at"
)

func (e CreditNotesSortBy) ToPointer() *CreditNotesSortBy {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CreditNotesSortBy) IsExact() bool {
	if e != nil {
		switch *e {
		case "created_at", "updated_at":
			return true
		}
	}
	return false
}

type CreditNotesSort struct {
	// The field on which to sort the Customers
	By *CreditNotesSortBy `queryParam:"name=by"`
	// The direction in which to sort the results
	Direction *SortDirection `default:"asc" queryParam:"name=direction"`
}

func (c CreditNotesSort) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditNotesSort) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditNotesSort) GetBy() *CreditNotesSortBy {
	if c == nil {
		return nil
	}
	return c.By
}

func (c *CreditNotesSort) GetDirection() *SortDirection {
	if c == nil {
		return nil
	}
	return c.Direction
}
