// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type CreditNotesFilter struct {
	// Return records with a row ID greater than or equal to the given value
	IDSince      *string    `queryParam:"name=id_since"`
	UpdatedSince *time.Time `queryParam:"name=updated_since"`
}

func (c CreditNotesFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditNotesFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditNotesFilter) GetIDSince() *string {
	if c == nil {
		return nil
	}
	return c.IDSince
}

func (c *CreditNotesFilter) GetUpdatedSince() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedSince
}
