// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
)

// CustomersSortBy - The field on which to sort the Customers
type CustomersSortBy string

const (
	CustomersSortByCreatedAt CustomersSortBy = "created_at"
	CustomersSortByUpdatedAt CustomersSortBy = "updated_at"
)

func (e CustomersSortBy) ToPointer() *CustomersSortBy {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CustomersSortBy) IsExact() bool {
	if e != nil {
		switch *e {
		case "created_at", "updated_at":
			return true
		}
	}
	return false
}

type CustomersSort struct {
	// The field on which to sort the Customers
	By *CustomersSortBy `queryParam:"name=by"`
	// The direction in which to sort the results
	Direction *SortDirection `default:"asc" queryParam:"name=direction"`
}

func (c CustomersSort) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomersSort) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomersSort) GetBy() *CustomersSortBy {
	if c == nil {
		return nil
	}
	return c.By
}

func (c *CustomersSort) GetDirection() *SortDirection {
	if c == nil {
		return nil
	}
	return c.Direction
}
