// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeleteConsumerResponseData struct {
	// Unique consumer identifier. You can freely choose a consumer ID yourself. Most of the time, this is an ID of your internal data model that represents a user or account in your system (for example account:12345). If the consumer doesn't exist yet, Vault will upsert a consumer based on your ID.
	ConsumerID *string `json:"consumer_id,omitempty"`
}

func (d *DeleteConsumerResponseData) GetConsumerID() *string {
	if d == nil {
		return nil
	}
	return d.ConsumerID
}

// DeleteConsumerResponse - Consumer deleted
type DeleteConsumerResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string                     `json:"status"`
	Data   DeleteConsumerResponseData `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (d *DeleteConsumerResponse) GetStatusCode() int64 {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteConsumerResponse) GetStatus() string {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeleteConsumerResponse) GetData() DeleteConsumerResponseData {
	if d == nil {
		return DeleteConsumerResponseData{}
	}
	return d.Data
}

func (d *DeleteConsumerResponse) GetRaw() map[string]any {
	if d == nil {
		return nil
	}
	return d.Raw
}
