// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DeleteWebhookResponse - Webhooks
type DeleteWebhookResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string  `json:"status"`
	Data   Webhook `json:"data"`
}

func (o *DeleteWebhookResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteWebhookResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *DeleteWebhookResponse) GetData() Webhook {
	if o == nil {
		return Webhook{}
	}
	return o.Data
}
