// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type Department struct {
	// A unique identifier for an object.
	ID *string `json:"id,omitempty"`
	// Parent ID
	ParentID *string `json:"parent_id,omitempty"`
	// Department name
	Name        *string `json:"name,omitempty"`
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	// When custom mappings are configured on the resource, the result is included here.
	CustomMappings map[string]any `json:"custom_mappings,omitempty"`
	// The user who last updated the object.
	UpdatedBy *string `json:"updated_by,omitempty"`
	// The user who created the object.
	CreatedBy *string `json:"created_by,omitempty"`
	// The date and time when the object was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// The date and time when the object was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
}

func (d Department) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Department) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *Department) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *Department) GetParentID() *string {
	if d == nil {
		return nil
	}
	return d.ParentID
}

func (d *Department) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *Department) GetCode() *string {
	if d == nil {
		return nil
	}
	return d.Code
}

func (d *Department) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *Department) GetCustomMappings() map[string]any {
	if d == nil {
		return nil
	}
	return d.CustomMappings
}

func (d *Department) GetUpdatedBy() *string {
	if d == nil {
		return nil
	}
	return d.UpdatedBy
}

func (d *Department) GetCreatedBy() *string {
	if d == nil {
		return nil
	}
	return d.CreatedBy
}

func (d *Department) GetUpdatedAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.UpdatedAt
}

func (d *Department) GetCreatedAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.CreatedAt
}

func (d *Department) GetPassThrough() []PassThroughBody {
	if d == nil {
		return nil
	}
	return d.PassThrough
}
