// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DeprecatedLinkedSupplierInput - The supplier this entity is linked to.
//
// Deprecated: This field is deprecated and may be removed in a future version..
type DeprecatedLinkedSupplierInput struct {
	// The display name of the supplier.
	DisplayName *string  `json:"display_name,omitempty"`
	Address     *Address `json:"address,omitempty"`
}

func (d *DeprecatedLinkedSupplierInput) GetDisplayName() *string {
	if d == nil {
		return nil
	}
	return d.DisplayName
}

func (d *DeprecatedLinkedSupplierInput) GetAddress() *Address {
	if d == nil {
		return nil
	}
	return d.Address
}
