// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type EcommerceStore struct {
	// A unique identifier for an object.
	ID string `json:"id"`
	// The store's name
	Name *string `json:"name,omitempty"`
	// The store's website URL
	StoreURL *string `json:"store_url,omitempty"`
	// The store's admin login URL
	AdminURL *string `json:"admin_url,omitempty"`
	// When custom mappings are configured on the resource, the result is included here.
	CustomMappings map[string]any `json:"custom_mappings,omitempty"`
	// The date and time when the object was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The date and time when the object was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

func (e EcommerceStore) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EcommerceStore) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (e *EcommerceStore) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EcommerceStore) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *EcommerceStore) GetStoreURL() *string {
	if e == nil {
		return nil
	}
	return e.StoreURL
}

func (e *EcommerceStore) GetAdminURL() *string {
	if e == nil {
		return nil
	}
	return e.AdminURL
}

func (e *EcommerceStore) GetCustomMappings() map[string]any {
	if e == nil {
		return nil
	}
	return e.CustomMappings
}

func (e *EcommerceStore) GetCreatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *EcommerceStore) GetUpdatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.UpdatedAt
}
