// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EcommerceAddress - An object representing a shipping or billing address.
type EcommerceAddress struct {
	// Address line 1 of the billing address.
	Line1 *string `json:"line1,omitempty"`
	// Address line 2 of the billing address.
	Line2 *string `json:"line2,omitempty"`
	// Company name of the customer
	CompanyName *string `json:"company_name,omitempty"`
	// City of the billing address.
	City *string `json:"city,omitempty"`
	// State/province of the billing address.
	State *string `json:"state,omitempty"`
	// Postal/ZIP code of the billing address.
	PostalCode *string `json:"postal_code,omitempty"`
	// Country of the billing address.
	Country *string `json:"country,omitempty"`
}

func (e *EcommerceAddress) GetLine1() *string {
	if e == nil {
		return nil
	}
	return e.Line1
}

func (e *EcommerceAddress) GetLine2() *string {
	if e == nil {
		return nil
	}
	return e.Line2
}

func (e *EcommerceAddress) GetCompanyName() *string {
	if e == nil {
		return nil
	}
	return e.CompanyName
}

func (e *EcommerceAddress) GetCity() *string {
	if e == nil {
		return nil
	}
	return e.City
}

func (e *EcommerceAddress) GetState() *string {
	if e == nil {
		return nil
	}
	return e.State
}

func (e *EcommerceAddress) GetPostalCode() *string {
	if e == nil {
		return nil
	}
	return e.PostalCode
}

func (e *EcommerceAddress) GetCountry() *string {
	if e == nil {
		return nil
	}
	return e.Country
}
