// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EcommerceProductsFilter struct {
	// Product name to filter on
	Name *string `queryParam:"name=name"`
	// Minimum date the product was last modified
	UpdatedSince *string `queryParam:"name=updated_since"`
	// Minimum date the product was created
	CreatedSince *string `queryParam:"name=created_since"`
}

func (e *EcommerceProductsFilter) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *EcommerceProductsFilter) GetUpdatedSince() *string {
	if e == nil {
		return nil
	}
	return e.UpdatedSince
}

func (e *EcommerceProductsFilter) GetCreatedSince() *string {
	if e == nil {
		return nil
	}
	return e.CreatedSince
}
