// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OptionsObj struct {
	// A unique identifier for the option.
	ID *string `json:"id,omitempty"`
	// The name of the option.
	Name *string `json:"name,omitempty"`
	// The value of the option.
	Value *string `json:"value,omitempty"`
}

func (o *OptionsObj) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OptionsObj) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *OptionsObj) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

// EcommerceOrderLineItem - A single line item of an ecommerce order, representing a product or variant with associated options, quantity, and pricing information.
type EcommerceOrderLineItem struct {
	// A unique identifier for an object.
	ID *string `json:"id,omitempty"`
	// A unique identifier for the product associated with the line item.
	ProductID *string `json:"product_id,omitempty"`
	// A unique identifier for the variant of the product associated with the line item, if applicable.
	VariantID *string `json:"variant_id,omitempty"`
	// The SKU of the product or variant associated with the line item.
	Sku *string `json:"sku,omitempty"`
	// The name of the product or variant associated with the line item.
	Name *string `json:"name,omitempty"`
	// The description of the product or variant associated with the line item.
	Description *string      `json:"description,omitempty"`
	Options     []OptionsObj `json:"options,omitempty"`
	// The quantity of the product or variant associated with the line item.
	Quantity *string `json:"quantity"`
	// The unit price of the product or variant associated with the line item.
	UnitPrice *string `json:"unit_price,omitempty"`
	// The tax rate applied to the product or variant associated with the line item.
	TaxRate *string `json:"tax_rate,omitempty"`
	// The total tax amount applied to the product or variant associated with the line item.
	TaxAmount *string `json:"tax_amount,omitempty"`
	// Whether the line item has been refunded.
	IsRefunded *bool `json:"is_refunded,omitempty"`
	// The amount of the line item that has been refunded.
	RefundedAmount *string `json:"refunded_amount,omitempty"`
	// The quantity of the line item that has been refunded.
	RefundedQuantity *string `json:"refunded_quantity,omitempty"`
	// The sub total for the product(s) or variant associated with the line item, excluding taxes and discounts.
	SubTotal *string `json:"sub_total,omitempty"`
	// The total amount for the product(s) or variant associated with the line item, including taxes and discounts.
	TotalAmount *string             `json:"total_amount,omitempty"`
	Discounts   []EcommerceDiscount `json:"discounts,omitempty"`
}

func (e *EcommerceOrderLineItem) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EcommerceOrderLineItem) GetProductID() *string {
	if e == nil {
		return nil
	}
	return e.ProductID
}

func (e *EcommerceOrderLineItem) GetVariantID() *string {
	if e == nil {
		return nil
	}
	return e.VariantID
}

func (e *EcommerceOrderLineItem) GetSku() *string {
	if e == nil {
		return nil
	}
	return e.Sku
}

func (e *EcommerceOrderLineItem) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *EcommerceOrderLineItem) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *EcommerceOrderLineItem) GetOptions() []OptionsObj {
	if e == nil {
		return nil
	}
	return e.Options
}

func (e *EcommerceOrderLineItem) GetQuantity() *string {
	if e == nil {
		return nil
	}
	return e.Quantity
}

func (e *EcommerceOrderLineItem) GetUnitPrice() *string {
	if e == nil {
		return nil
	}
	return e.UnitPrice
}

func (e *EcommerceOrderLineItem) GetTaxRate() *string {
	if e == nil {
		return nil
	}
	return e.TaxRate
}

func (e *EcommerceOrderLineItem) GetTaxAmount() *string {
	if e == nil {
		return nil
	}
	return e.TaxAmount
}

func (e *EcommerceOrderLineItem) GetIsRefunded() *bool {
	if e == nil {
		return nil
	}
	return e.IsRefunded
}

func (e *EcommerceOrderLineItem) GetRefundedAmount() *string {
	if e == nil {
		return nil
	}
	return e.RefundedAmount
}

func (e *EcommerceOrderLineItem) GetRefundedQuantity() *string {
	if e == nil {
		return nil
	}
	return e.RefundedQuantity
}

func (e *EcommerceOrderLineItem) GetSubTotal() *string {
	if e == nil {
		return nil
	}
	return e.SubTotal
}

func (e *EcommerceOrderLineItem) GetTotalAmount() *string {
	if e == nil {
		return nil
	}
	return e.TotalAmount
}

func (e *EcommerceOrderLineItem) GetDiscounts() []EcommerceDiscount {
	if e == nil {
		return nil
	}
	return e.Discounts
}
