// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FlsaStatus - The FLSA status for this compensation.
type FlsaStatus string

const (
	FlsaStatusExempt            FlsaStatus = "exempt"
	FlsaStatusSalariedNonexempt FlsaStatus = "salaried-nonexempt"
	FlsaStatusNonexempt         FlsaStatus = "nonexempt"
	FlsaStatusOwner             FlsaStatus = "owner"
	FlsaStatusOther             FlsaStatus = "other"
)

func (e FlsaStatus) ToPointer() *FlsaStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FlsaStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "exempt", "salaried-nonexempt", "nonexempt", "owner", "other":
			return true
		}
	}
	return false
}

type EmployeeCompensation struct {
	// A unique identifier for an object.
	ID *string `json:"id,omitempty"`
	// The ID of the job to which the compensation belongs.
	JobID *string `json:"job_id,omitempty"`
	// The amount paid per payment unit.
	Rate *float64 `json:"rate,omitempty"`
	// Unit of measurement for employee compensation.
	PaymentUnit *PaymentUnit `json:"payment_unit,omitempty"`
	// Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
	Currency *Currency `json:"currency,omitempty"`
	// The FLSA status for this compensation.
	FlsaStatus *FlsaStatus `json:"flsa_status,omitempty"`
	// The date on which a change to an employee's compensation takes effect.
	EffectiveDate *string `json:"effective_date,omitempty"`
	// Frequency of employee compensation.
	PaymentFrequency *PaymentFrequency `json:"payment_frequency,omitempty"`
}

func (e *EmployeeCompensation) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EmployeeCompensation) GetJobID() *string {
	if e == nil {
		return nil
	}
	return e.JobID
}

func (e *EmployeeCompensation) GetRate() *float64 {
	if e == nil {
		return nil
	}
	return e.Rate
}

func (e *EmployeeCompensation) GetPaymentUnit() *PaymentUnit {
	if e == nil {
		return nil
	}
	return e.PaymentUnit
}

func (e *EmployeeCompensation) GetCurrency() *Currency {
	if e == nil {
		return nil
	}
	return e.Currency
}

func (e *EmployeeCompensation) GetFlsaStatus() *FlsaStatus {
	if e == nil {
		return nil
	}
	return e.FlsaStatus
}

func (e *EmployeeCompensation) GetEffectiveDate() *string {
	if e == nil {
		return nil
	}
	return e.EffectiveDate
}

func (e *EmployeeCompensation) GetPaymentFrequency() *PaymentFrequency {
	if e == nil {
		return nil
	}
	return e.PaymentFrequency
}

type EmployeeCompensationInput struct {
	// The amount paid per payment unit.
	Rate *float64 `json:"rate,omitempty"`
	// Unit of measurement for employee compensation.
	PaymentUnit *PaymentUnit `json:"payment_unit,omitempty"`
	// Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
	Currency *Currency `json:"currency,omitempty"`
	// The FLSA status for this compensation.
	FlsaStatus *FlsaStatus `json:"flsa_status,omitempty"`
	// The date on which a change to an employee's compensation takes effect.
	EffectiveDate *string `json:"effective_date,omitempty"`
	// Frequency of employee compensation.
	PaymentFrequency *PaymentFrequency `json:"payment_frequency,omitempty"`
}

func (e *EmployeeCompensationInput) GetRate() *float64 {
	if e == nil {
		return nil
	}
	return e.Rate
}

func (e *EmployeeCompensationInput) GetPaymentUnit() *PaymentUnit {
	if e == nil {
		return nil
	}
	return e.PaymentUnit
}

func (e *EmployeeCompensationInput) GetCurrency() *Currency {
	if e == nil {
		return nil
	}
	return e.Currency
}

func (e *EmployeeCompensationInput) GetFlsaStatus() *FlsaStatus {
	if e == nil {
		return nil
	}
	return e.FlsaStatus
}

func (e *EmployeeCompensationInput) GetEffectiveDate() *string {
	if e == nil {
		return nil
	}
	return e.EffectiveDate
}

func (e *EmployeeCompensationInput) GetPaymentFrequency() *PaymentFrequency {
	if e == nil {
		return nil
	}
	return e.PaymentFrequency
}
