// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EmployeesFilterEmploymentStatus - Employment status to filter on
type EmployeesFilterEmploymentStatus string

const (
	EmployeesFilterEmploymentStatusActive     EmployeesFilterEmploymentStatus = "active"
	EmployeesFilterEmploymentStatusInactive   EmployeesFilterEmploymentStatus = "inactive"
	EmployeesFilterEmploymentStatusTerminated EmployeesFilterEmploymentStatus = "terminated"
	EmployeesFilterEmploymentStatusOther      EmployeesFilterEmploymentStatus = "other"
)

func (e EmployeesFilterEmploymentStatus) ToPointer() *EmployeesFilterEmploymentStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EmployeesFilterEmploymentStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "inactive", "terminated", "other":
			return true
		}
	}
	return false
}

type EmployeesFilter struct {
	// Company ID to filter on
	CompanyID *string `queryParam:"name=company_id"`
	// Email to filter on
	Email *string `queryParam:"name=email"`
	// First Name to filter on
	FirstName *string `queryParam:"name=first_name"`
	// Job title to filter on
	Title *string `queryParam:"name=title"`
	// Last Name to filter on
	LastName *string `queryParam:"name=last_name"`
	// Manager id to filter on
	ManagerID *string `queryParam:"name=manager_id"`
	// Employment status to filter on
	EmploymentStatus *EmployeesFilterEmploymentStatus `queryParam:"name=employment_status"`
	// Employee number to filter on
	EmployeeNumber *string `queryParam:"name=employee_number"`
	// ID of the department to filter on
	DepartmentID *string `queryParam:"name=department_id"`
	// City to filter on
	City *string `queryParam:"name=city"`
	// Country to filter on
	Country *string `queryParam:"name=country"`
}

func (e *EmployeesFilter) GetCompanyID() *string {
	if e == nil {
		return nil
	}
	return e.CompanyID
}

func (e *EmployeesFilter) GetEmail() *string {
	if e == nil {
		return nil
	}
	return e.Email
}

func (e *EmployeesFilter) GetFirstName() *string {
	if e == nil {
		return nil
	}
	return e.FirstName
}

func (e *EmployeesFilter) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *EmployeesFilter) GetLastName() *string {
	if e == nil {
		return nil
	}
	return e.LastName
}

func (e *EmployeesFilter) GetManagerID() *string {
	if e == nil {
		return nil
	}
	return e.ManagerID
}

func (e *EmployeesFilter) GetEmploymentStatus() *EmployeesFilterEmploymentStatus {
	if e == nil {
		return nil
	}
	return e.EmploymentStatus
}

func (e *EmployeesFilter) GetEmployeeNumber() *string {
	if e == nil {
		return nil
	}
	return e.EmployeeNumber
}

func (e *EmployeesFilter) GetDepartmentID() *string {
	if e == nil {
		return nil
	}
	return e.DepartmentID
}

func (e *EmployeesFilter) GetCity() *string {
	if e == nil {
		return nil
	}
	return e.City
}

func (e *EmployeesFilter) GetCountry() *string {
	if e == nil {
		return nil
	}
	return e.Country
}
