// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetAPIResourceCoverageResponse - ApiResources
type GetAPIResourceCoverageResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string              `json:"status"`
	Data   APIResourceCoverage `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
	// Response metadata
	Meta *Meta `json:"meta,omitempty"`
	// Links to navigate to previous or next pages through the API
	Links *Links `json:"links,omitempty"`
}

func (g *GetAPIResourceCoverageResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAPIResourceCoverageResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetAPIResourceCoverageResponse) GetData() APIResourceCoverage {
	if g == nil {
		return APIResourceCoverage{}
	}
	return g.Data
}

func (g *GetAPIResourceCoverageResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}

func (g *GetAPIResourceCoverageResponse) GetMeta() *Meta {
	if g == nil {
		return nil
	}
	return g.Meta
}

func (g *GetAPIResourceCoverageResponse) GetLinks() *Links {
	if g == nil {
		return nil
	}
	return g.Links
}
