// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetCollectionResponse - Get a Collection
type GetCollectionResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string     `json:"operation"`
	Data      Collection `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (g *GetCollectionResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetCollectionResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetCollectionResponse) GetService() string {
	if g == nil {
		return ""
	}
	return g.Service
}

func (g *GetCollectionResponse) GetResource() string {
	if g == nil {
		return ""
	}
	return g.Resource
}

func (g *GetCollectionResponse) GetOperation() string {
	if g == nil {
		return ""
	}
	return g.Operation
}

func (g *GetCollectionResponse) GetData() Collection {
	if g == nil {
		return Collection{}
	}
	return g.Data
}

func (g *GetCollectionResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}
