// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetConnectorsResponse - Connectors
type GetConnectorsResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string      `json:"status"`
	Data   []Connector `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
	// Response metadata
	Meta *Meta `json:"meta,omitempty"`
	// Links to navigate to previous or next pages through the API
	Links *Links `json:"links,omitempty"`
}

func (g *GetConnectorsResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetConnectorsResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetConnectorsResponse) GetData() []Connector {
	if g == nil {
		return []Connector{}
	}
	return g.Data
}

func (g *GetConnectorsResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}

func (g *GetConnectorsResponse) GetMeta() *Meta {
	if g == nil {
		return nil
	}
	return g.Meta
}

func (g *GetConnectorsResponse) GetLinks() *Links {
	if g == nil {
		return nil
	}
	return g.Links
}
