// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetCustomObjectSchemaResponse - Custom object schema
type GetCustomObjectSchemaResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string             `json:"operation"`
	Data      CustomObjectSchema `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (g *GetCustomObjectSchemaResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetCustomObjectSchemaResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetCustomObjectSchemaResponse) GetService() string {
	if g == nil {
		return ""
	}
	return g.Service
}

func (g *GetCustomObjectSchemaResponse) GetResource() string {
	if g == nil {
		return ""
	}
	return g.Resource
}

func (g *GetCustomObjectSchemaResponse) GetOperation() string {
	if g == nil {
		return ""
	}
	return g.Operation
}

func (g *GetCustomObjectSchemaResponse) GetData() CustomObjectSchema {
	if g == nil {
		return CustomObjectSchema{}
	}
	return g.Data
}

func (g *GetCustomObjectSchemaResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}
