// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetCustomObjectResponse - Custom object
type GetCustomObjectResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string       `json:"operation"`
	Data      CustomObject `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (g *GetCustomObjectResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetCustomObjectResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetCustomObjectResponse) GetService() string {
	if g == nil {
		return ""
	}
	return g.Service
}

func (g *GetCustomObjectResponse) GetResource() string {
	if g == nil {
		return ""
	}
	return g.Resource
}

func (g *GetCustomObjectResponse) GetOperation() string {
	if g == nil {
		return ""
	}
	return g.Operation
}

func (g *GetCustomObjectResponse) GetData() CustomObject {
	if g == nil {
		return CustomObject{}
	}
	return g.Data
}

func (g *GetCustomObjectResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}
