// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetExpenseResponse - Expenses
type GetExpenseResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string  `json:"operation"`
	Data      Expense `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (g *GetExpenseResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetExpenseResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetExpenseResponse) GetService() string {
	if g == nil {
		return ""
	}
	return g.Service
}

func (g *GetExpenseResponse) GetResource() string {
	if g == nil {
		return ""
	}
	return g.Resource
}

func (g *GetExpenseResponse) GetOperation() string {
	if g == nil {
		return ""
	}
	return g.Operation
}

func (g *GetExpenseResponse) GetData() Expense {
	if g == nil {
		return Expense{}
	}
	return g.Data
}

func (g *GetExpenseResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}
