// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetPayrollResponse - Payrolls
type GetPayrollResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string  `json:"operation"`
	Data      Payroll `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (g *GetPayrollResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPayrollResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetPayrollResponse) GetService() string {
	if g == nil {
		return ""
	}
	return g.Service
}

func (g *GetPayrollResponse) GetResource() string {
	if g == nil {
		return ""
	}
	return g.Resource
}

func (g *GetPayrollResponse) GetOperation() string {
	if g == nil {
		return ""
	}
	return g.Operation
}

func (g *GetPayrollResponse) GetData() Payroll {
	if g == nil {
		return Payroll{}
	}
	return g.Data
}

func (g *GetPayrollResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}
