// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetSuppliersResponse - Suppliers
type GetSuppliersResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string     `json:"operation"`
	Data      []Supplier `json:"data"`
	// Response metadata
	Meta *Meta `json:"meta,omitempty"`
	// Links to navigate to previous or next pages through the API
	Links *Links `json:"links,omitempty"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (g *GetSuppliersResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSuppliersResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetSuppliersResponse) GetService() string {
	if g == nil {
		return ""
	}
	return g.Service
}

func (g *GetSuppliersResponse) GetResource() string {
	if g == nil {
		return ""
	}
	return g.Resource
}

func (g *GetSuppliersResponse) GetOperation() string {
	if g == nil {
		return ""
	}
	return g.Operation
}

func (g *GetSuppliersResponse) GetData() []Supplier {
	if g == nil {
		return []Supplier{}
	}
	return g.Data
}

func (g *GetSuppliersResponse) GetMeta() *Meta {
	if g == nil {
		return nil
	}
	return g.Meta
}

func (g *GetSuppliersResponse) GetLinks() *Links {
	if g == nil {
		return nil
	}
	return g.Links
}

func (g *GetSuppliersResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}
