// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetTrackingCategoriesResponse - Tracking categories
type GetTrackingCategoriesResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string             `json:"operation"`
	Data      []TrackingCategory `json:"data"`
	// Response metadata
	Meta *Meta `json:"meta,omitempty"`
	// Links to navigate to previous or next pages through the API
	Links *Links `json:"links,omitempty"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (g *GetTrackingCategoriesResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetTrackingCategoriesResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetTrackingCategoriesResponse) GetService() string {
	if g == nil {
		return ""
	}
	return g.Service
}

func (g *GetTrackingCategoriesResponse) GetResource() string {
	if g == nil {
		return ""
	}
	return g.Resource
}

func (g *GetTrackingCategoriesResponse) GetOperation() string {
	if g == nil {
		return ""
	}
	return g.Operation
}

func (g *GetTrackingCategoriesResponse) GetData() []TrackingCategory {
	if g == nil {
		return []TrackingCategory{}
	}
	return g.Data
}

func (g *GetTrackingCategoriesResponse) GetMeta() *Meta {
	if g == nil {
		return nil
	}
	return g.Meta
}

func (g *GetTrackingCategoriesResponse) GetLinks() *Links {
	if g == nil {
		return nil
	}
	return g.Links
}

func (g *GetTrackingCategoriesResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}
