// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetUserResponse - User
type GetUserResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string `json:"operation"`
	Data      User   `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (g *GetUserResponse) GetStatusCode() int64 {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetUserResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetUserResponse) GetService() string {
	if g == nil {
		return ""
	}
	return g.Service
}

func (g *GetUserResponse) GetResource() string {
	if g == nil {
		return ""
	}
	return g.Resource
}

func (g *GetUserResponse) GetOperation() string {
	if g == nil {
		return ""
	}
	return g.Operation
}

func (g *GetUserResponse) GetData() User {
	if g == nil {
		return User{}
	}
	return g.Data
}

func (g *GetUserResponse) GetRaw() map[string]any {
	if g == nil {
		return nil
	}
	return g.Raw
}
