// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

// JournalEntryCreateInputStatus - Journal entry status
type JournalEntryCreateInputStatus string

const (
	JournalEntryCreateInputStatusDraft           JournalEntryCreateInputStatus = "draft"
	JournalEntryCreateInputStatusPendingApproval JournalEntryCreateInputStatus = "pending_approval"
	JournalEntryCreateInputStatusApproved        JournalEntryCreateInputStatus = "approved"
	JournalEntryCreateInputStatusPosted          JournalEntryCreateInputStatus = "posted"
	JournalEntryCreateInputStatusVoided          JournalEntryCreateInputStatus = "voided"
	JournalEntryCreateInputStatusRejected        JournalEntryCreateInputStatus = "rejected"
	JournalEntryCreateInputStatusDeleted         JournalEntryCreateInputStatus = "deleted"
	JournalEntryCreateInputStatusOther           JournalEntryCreateInputStatus = "other"
)

func (e JournalEntryCreateInputStatus) ToPointer() *JournalEntryCreateInputStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *JournalEntryCreateInputStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "draft", "pending_approval", "approved", "posted", "voided", "rejected", "deleted", "other":
			return true
		}
	}
	return false
}

// JournalEntryCreateInput - The writable shape of JournalEntry for a batch create. Identical to [JournalEntry](the model returned on reads) with the read-only properties removed — the same properties the single-record create endpoint rejects, so a batched record and a single-record create accept exactly the same body.
type JournalEntryCreateInput struct {
	// Display ID of the journal entry
	DisplayID *string `json:"display_id,omitempty"`
	// Journal entry title
	Title *string `json:"title,omitempty"`
	// Currency Exchange Rate at the time entity was recorded/generated.
	CurrencyRate *float64 `json:"currency_rate,omitempty"`
	// Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
	Currency *Currency `json:"currency,omitempty"`
	// The company ID the transaction belongs to
	CompanyID  *string                `json:"company_id,omitempty"`
	Subsidiary *LinkedSubsidiaryInput `json:"subsidiary,omitempty"`
	// Requires a minimum of 2 line items that sum to 0
	LineItems []JournalEntryLineItemInput `json:"line_items,omitempty"`
	// Journal entry status
	Status *JournalEntryCreateInputStatus `json:"status,omitempty"`
	// Reference for the journal entry.
	Memo *string `json:"memo,omitempty"`
	// This is the date on which the journal entry was added. This can be different from the creation date and can also be backdated.
	PostedAt *time.Time `json:"posted_at,omitempty"`
	// Journal symbol of the entry. For example IND for indirect costs. Where supported, list /accounting/journals to discover available journals and their posting rules. For Exact Online, supply the journal code, not its id.
	JournalSymbol *string `json:"journal_symbol,omitempty"`
	// Deprecated — use line_items[].tax_type for per-line tax applicability. Kept as fallback: applies to all lines that do not set their own tax_type.
	//
	// Deprecated: Deprecated — use line_items[]..
	TaxType *string `json:"tax_type,omitempty"`
	// Applicable tax id/code override if tax is not supplied on a line item basis.
	TaxCode *string `json:"tax_code,omitempty"`
	// Journal entry number.
	Number *string `json:"number,omitempty"`
	// A list of linked tracking categories.
	TrackingCategories []*LinkedTrackingCategory `json:"tracking_categories,omitempty"`
	// Accounting period
	AccountingPeriod *string `json:"accounting_period,omitempty"`
	// Amounts are including tax
	TaxInclusive *bool `json:"tax_inclusive,omitempty"`
	// Files attached to this journal entry. Use the attachments endpoints with reference_type=journal-entry and this entry's id where the connector supports it.
	Attachments []*LinkedAttachment `json:"attachments,omitempty"`
	// The source type of the journal entry
	SourceType *string `json:"source_type,omitempty"`
	// A unique identifier for the source of the journal entry
	SourceID *string `json:"source_id,omitempty"`
	// A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.
	RowVersion   *string       `json:"row_version,omitempty"`
	CustomFields []CustomField `json:"custom_fields,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
}

func (j JournalEntryCreateInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JournalEntryCreateInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *JournalEntryCreateInput) GetDisplayID() *string {
	if j == nil {
		return nil
	}
	return j.DisplayID
}

func (j *JournalEntryCreateInput) GetTitle() *string {
	if j == nil {
		return nil
	}
	return j.Title
}

func (j *JournalEntryCreateInput) GetCurrencyRate() *float64 {
	if j == nil {
		return nil
	}
	return j.CurrencyRate
}

func (j *JournalEntryCreateInput) GetCurrency() *Currency {
	if j == nil {
		return nil
	}
	return j.Currency
}

func (j *JournalEntryCreateInput) GetCompanyID() *string {
	if j == nil {
		return nil
	}
	return j.CompanyID
}

func (j *JournalEntryCreateInput) GetSubsidiary() *LinkedSubsidiaryInput {
	if j == nil {
		return nil
	}
	return j.Subsidiary
}

func (j *JournalEntryCreateInput) GetLineItems() []JournalEntryLineItemInput {
	if j == nil {
		return nil
	}
	return j.LineItems
}

func (j *JournalEntryCreateInput) GetStatus() *JournalEntryCreateInputStatus {
	if j == nil {
		return nil
	}
	return j.Status
}

func (j *JournalEntryCreateInput) GetMemo() *string {
	if j == nil {
		return nil
	}
	return j.Memo
}

func (j *JournalEntryCreateInput) GetPostedAt() *time.Time {
	if j == nil {
		return nil
	}
	return j.PostedAt
}

func (j *JournalEntryCreateInput) GetJournalSymbol() *string {
	if j == nil {
		return nil
	}
	return j.JournalSymbol
}

func (j *JournalEntryCreateInput) GetTaxType() *string {
	if j == nil {
		return nil
	}
	return j.TaxType
}

func (j *JournalEntryCreateInput) GetTaxCode() *string {
	if j == nil {
		return nil
	}
	return j.TaxCode
}

func (j *JournalEntryCreateInput) GetNumber() *string {
	if j == nil {
		return nil
	}
	return j.Number
}

func (j *JournalEntryCreateInput) GetTrackingCategories() []*LinkedTrackingCategory {
	if j == nil {
		return nil
	}
	return j.TrackingCategories
}

func (j *JournalEntryCreateInput) GetAccountingPeriod() *string {
	if j == nil {
		return nil
	}
	return j.AccountingPeriod
}

func (j *JournalEntryCreateInput) GetTaxInclusive() *bool {
	if j == nil {
		return nil
	}
	return j.TaxInclusive
}

func (j *JournalEntryCreateInput) GetAttachments() []*LinkedAttachment {
	if j == nil {
		return nil
	}
	return j.Attachments
}

func (j *JournalEntryCreateInput) GetSourceType() *string {
	if j == nil {
		return nil
	}
	return j.SourceType
}

func (j *JournalEntryCreateInput) GetSourceID() *string {
	if j == nil {
		return nil
	}
	return j.SourceID
}

func (j *JournalEntryCreateInput) GetRowVersion() *string {
	if j == nil {
		return nil
	}
	return j.RowVersion
}

func (j *JournalEntryCreateInput) GetCustomFields() []CustomField {
	if j == nil {
		return nil
	}
	return j.CustomFields
}

func (j *JournalEntryCreateInput) GetPassThrough() []PassThroughBody {
	if j == nil {
		return nil
	}
	return j.PassThrough
}
