// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"github.com/apideck-libraries/sdk-go/types"
)

// LedgerAccountCreateInputClassification - The classification of account.
type LedgerAccountCreateInputClassification string

const (
	LedgerAccountCreateInputClassificationAsset        LedgerAccountCreateInputClassification = "asset"
	LedgerAccountCreateInputClassificationEquity       LedgerAccountCreateInputClassification = "equity"
	LedgerAccountCreateInputClassificationExpense      LedgerAccountCreateInputClassification = "expense"
	LedgerAccountCreateInputClassificationLiability    LedgerAccountCreateInputClassification = "liability"
	LedgerAccountCreateInputClassificationRevenue      LedgerAccountCreateInputClassification = "revenue"
	LedgerAccountCreateInputClassificationIncome       LedgerAccountCreateInputClassification = "income"
	LedgerAccountCreateInputClassificationOtherIncome  LedgerAccountCreateInputClassification = "other_income"
	LedgerAccountCreateInputClassificationOtherExpense LedgerAccountCreateInputClassification = "other_expense"
	LedgerAccountCreateInputClassificationCostsOfSales LedgerAccountCreateInputClassification = "costs_of_sales"
	LedgerAccountCreateInputClassificationOther        LedgerAccountCreateInputClassification = "other"
)

func (e LedgerAccountCreateInputClassification) ToPointer() *LedgerAccountCreateInputClassification {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LedgerAccountCreateInputClassification) IsExact() bool {
	if e != nil {
		switch *e {
		case "asset", "equity", "expense", "liability", "revenue", "income", "other_income", "other_expense", "costs_of_sales", "other":
			return true
		}
	}
	return false
}

// LedgerAccountCreateInputType - The type of account.
type LedgerAccountCreateInputType string

const (
	LedgerAccountCreateInputTypeAccountsPayable     LedgerAccountCreateInputType = "accounts_payable"
	LedgerAccountCreateInputTypeAccountsReceivable  LedgerAccountCreateInputType = "accounts_receivable"
	LedgerAccountCreateInputTypeBalancesheet        LedgerAccountCreateInputType = "balancesheet"
	LedgerAccountCreateInputTypeBank                LedgerAccountCreateInputType = "bank"
	LedgerAccountCreateInputTypeCostsOfSales        LedgerAccountCreateInputType = "costs_of_sales"
	LedgerAccountCreateInputTypeCreditCard          LedgerAccountCreateInputType = "credit_card"
	LedgerAccountCreateInputTypeCurrentAsset        LedgerAccountCreateInputType = "current_asset"
	LedgerAccountCreateInputTypeCurrentLiability    LedgerAccountCreateInputType = "current_liability"
	LedgerAccountCreateInputTypeEquity              LedgerAccountCreateInputType = "equity"
	LedgerAccountCreateInputTypeExpense             LedgerAccountCreateInputType = "expense"
	LedgerAccountCreateInputTypeFixedAsset          LedgerAccountCreateInputType = "fixed_asset"
	LedgerAccountCreateInputTypeNonCurrentAsset     LedgerAccountCreateInputType = "non_current_asset"
	LedgerAccountCreateInputTypeNonCurrentLiability LedgerAccountCreateInputType = "non_current_liability"
	LedgerAccountCreateInputTypeOtherAsset          LedgerAccountCreateInputType = "other_asset"
	LedgerAccountCreateInputTypeOtherExpense        LedgerAccountCreateInputType = "other_expense"
	LedgerAccountCreateInputTypeOtherIncome         LedgerAccountCreateInputType = "other_income"
	LedgerAccountCreateInputTypeOtherLiability      LedgerAccountCreateInputType = "other_liability"
	LedgerAccountCreateInputTypeRevenue             LedgerAccountCreateInputType = "revenue"
	LedgerAccountCreateInputTypeSales               LedgerAccountCreateInputType = "sales"
	LedgerAccountCreateInputTypeOther               LedgerAccountCreateInputType = "other"
)

func (e LedgerAccountCreateInputType) ToPointer() *LedgerAccountCreateInputType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LedgerAccountCreateInputType) IsExact() bool {
	if e != nil {
		switch *e {
		case "accounts_payable", "accounts_receivable", "balancesheet", "bank", "costs_of_sales", "credit_card", "current_asset", "current_liability", "equity", "expense", "fixed_asset", "non_current_asset", "non_current_liability", "other_asset", "other_expense", "other_income", "other_liability", "revenue", "sales", "other":
			return true
		}
	}
	return false
}

// LedgerAccountCreateInputAccountStatus - The status of the account.
type LedgerAccountCreateInputAccountStatus string

const (
	LedgerAccountCreateInputAccountStatusActive   LedgerAccountCreateInputAccountStatus = "active"
	LedgerAccountCreateInputAccountStatusInactive LedgerAccountCreateInputAccountStatus = "inactive"
	LedgerAccountCreateInputAccountStatusArchived LedgerAccountCreateInputAccountStatus = "archived"
)

func (e LedgerAccountCreateInputAccountStatus) ToPointer() *LedgerAccountCreateInputAccountStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LedgerAccountCreateInputAccountStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "inactive", "archived":
			return true
		}
	}
	return false
}

type LedgerAccountCreateInputParentAccount struct {
	// The ID of the parent account.
	ID *string `json:"id,omitempty"`
	// The name of the parent account.
	Name *string `json:"name,omitempty"`
	// The human readable display ID used when displaying the parent account
	DisplayID *string `json:"display_id,omitempty"`
}

func (l *LedgerAccountCreateInputParentAccount) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LedgerAccountCreateInputParentAccount) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LedgerAccountCreateInputParentAccount) GetDisplayID() *string {
	if l == nil {
		return nil
	}
	return l.DisplayID
}

type LedgerAccountCreateInputSubsidiaries struct {
	// The ID of the subsidiary.
	ID *string `json:"id,omitempty"`
}

func (l *LedgerAccountCreateInputSubsidiaries) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

// LedgerAccountCreateInput - The writable shape of LedgerAccount for a batch create. Identical to [LedgerAccount](the model returned on reads) with the read-only properties removed — the same properties the single-record create endpoint rejects, so a batched record and a single-record create accept exactly the same body.
type LedgerAccountCreateInput struct {
	// The human readable display ID used when displaying the account
	DisplayID *string `json:"display_id,omitempty"`
	// The nominal code of the ledger account.
	//
	// Deprecated: This field is deprecated and may be removed in a future version..
	NominalCode *string `json:"nominal_code,omitempty"`
	// The code assigned to the account.
	Code *string `json:"code,omitempty"`
	// The classification of account.
	Classification *LedgerAccountCreateInputClassification `json:"classification,omitempty"`
	// The type of account.
	Type *LedgerAccountCreateInputType `json:"type,omitempty"`
	// The sub type of account.
	SubType *string `json:"sub_type,omitempty"`
	// The name of the account.
	Name *string `json:"name,omitempty"`
	// The fully qualified name of the account.
	FullyQualifiedName *string `json:"fully_qualified_name,omitempty"`
	// The description of the account.
	Description *string `json:"description,omitempty"`
	// The opening balance of the account.
	OpeningBalance *float64 `json:"opening_balance,omitempty"`
	// The current balance of the account.
	CurrentBalance *float64 `json:"current_balance,omitempty"`
	// Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
	Currency *Currency `json:"currency,omitempty"`
	// The tax type of the account.
	TaxType *string             `json:"tax_type,omitempty"`
	TaxRate *LinkedTaxRateInput `json:"tax_rate,omitempty"`
	Level   *float64            `json:"level,omitempty"`
	// Whether the account is active or not.
	Active *bool `json:"active,omitempty"`
	// The status of the account.
	Status *LedgerAccountCreateInputAccountStatus `json:"status,omitempty"`
	// Whether the account is a header or not.
	Header        *bool                                  `json:"header,omitempty"`
	BankAccount   *BankAccount                           `json:"bank_account,omitempty"`
	ParentAccount *LedgerAccountCreateInputParentAccount `json:"parent_account,omitempty"`
	// Whether the account is a sub account or not.
	SubAccount *bool `json:"sub_account,omitempty"`
	// Reconciliation Date means the last calendar day of each Reconciliation Period.
	LastReconciliationDate *types.Date `json:"last_reconciliation_date,omitempty"`
	// The subsidiaries the account belongs to.
	Subsidiaries []LedgerAccountCreateInputSubsidiaries `json:"subsidiaries,omitempty"`
	CustomFields []CustomField                          `json:"custom_fields,omitempty"`
	// A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.
	RowVersion *string `json:"row_version,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
}

func (l LedgerAccountCreateInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LedgerAccountCreateInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LedgerAccountCreateInput) GetDisplayID() *string {
	if l == nil {
		return nil
	}
	return l.DisplayID
}

func (l *LedgerAccountCreateInput) GetNominalCode() *string {
	if l == nil {
		return nil
	}
	return l.NominalCode
}

func (l *LedgerAccountCreateInput) GetCode() *string {
	if l == nil {
		return nil
	}
	return l.Code
}

func (l *LedgerAccountCreateInput) GetClassification() *LedgerAccountCreateInputClassification {
	if l == nil {
		return nil
	}
	return l.Classification
}

func (l *LedgerAccountCreateInput) GetType() *LedgerAccountCreateInputType {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *LedgerAccountCreateInput) GetSubType() *string {
	if l == nil {
		return nil
	}
	return l.SubType
}

func (l *LedgerAccountCreateInput) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LedgerAccountCreateInput) GetFullyQualifiedName() *string {
	if l == nil {
		return nil
	}
	return l.FullyQualifiedName
}

func (l *LedgerAccountCreateInput) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *LedgerAccountCreateInput) GetOpeningBalance() *float64 {
	if l == nil {
		return nil
	}
	return l.OpeningBalance
}

func (l *LedgerAccountCreateInput) GetCurrentBalance() *float64 {
	if l == nil {
		return nil
	}
	return l.CurrentBalance
}

func (l *LedgerAccountCreateInput) GetCurrency() *Currency {
	if l == nil {
		return nil
	}
	return l.Currency
}

func (l *LedgerAccountCreateInput) GetTaxType() *string {
	if l == nil {
		return nil
	}
	return l.TaxType
}

func (l *LedgerAccountCreateInput) GetTaxRate() *LinkedTaxRateInput {
	if l == nil {
		return nil
	}
	return l.TaxRate
}

func (l *LedgerAccountCreateInput) GetLevel() *float64 {
	if l == nil {
		return nil
	}
	return l.Level
}

func (l *LedgerAccountCreateInput) GetActive() *bool {
	if l == nil {
		return nil
	}
	return l.Active
}

func (l *LedgerAccountCreateInput) GetStatus() *LedgerAccountCreateInputAccountStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *LedgerAccountCreateInput) GetHeader() *bool {
	if l == nil {
		return nil
	}
	return l.Header
}

func (l *LedgerAccountCreateInput) GetBankAccount() *BankAccount {
	if l == nil {
		return nil
	}
	return l.BankAccount
}

func (l *LedgerAccountCreateInput) GetParentAccount() *LedgerAccountCreateInputParentAccount {
	if l == nil {
		return nil
	}
	return l.ParentAccount
}

func (l *LedgerAccountCreateInput) GetSubAccount() *bool {
	if l == nil {
		return nil
	}
	return l.SubAccount
}

func (l *LedgerAccountCreateInput) GetLastReconciliationDate() *types.Date {
	if l == nil {
		return nil
	}
	return l.LastReconciliationDate
}

func (l *LedgerAccountCreateInput) GetSubsidiaries() []LedgerAccountCreateInputSubsidiaries {
	if l == nil {
		return nil
	}
	return l.Subsidiaries
}

func (l *LedgerAccountCreateInput) GetCustomFields() []CustomField {
	if l == nil {
		return nil
	}
	return l.CustomFields
}

func (l *LedgerAccountCreateInput) GetRowVersion() *string {
	if l == nil {
		return nil
	}
	return l.RowVersion
}

func (l *LedgerAccountCreateInput) GetPassThrough() []PassThroughBody {
	if l == nil {
		return nil
	}
	return l.PassThrough
}
