// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkedSubsidiary struct {
	// A unique identifier for an object.
	ID *string `json:"id,omitempty"`
	// Id to be displayed.
	DisplayID *string `json:"display_id,omitempty"`
	// The name of the resource.
	Name *string `json:"name,omitempty"`
}

func (l *LinkedSubsidiary) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LinkedSubsidiary) GetDisplayID() *string {
	if l == nil {
		return nil
	}
	return l.DisplayID
}

func (l *LinkedSubsidiary) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}
