// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkedTaxDetail struct {
	// The type of tax.
	Type *string `json:"type,omitempty"`
	// The number of the tax.
	Number *string `json:"number,omitempty"`
	// Whether the tax is a transaction tax.
	IsTransactionTax *bool `json:"is_transaction_tax,omitempty"`
	// Whether the tax is a primary tax.
	IsPrimaryTax *bool `json:"is_primary_tax,omitempty"`
}

func (l *LinkedTaxDetail) GetType() *string {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *LinkedTaxDetail) GetNumber() *string {
	if l == nil {
		return nil
	}
	return l.Number
}

func (l *LinkedTaxDetail) GetIsTransactionTax() *bool {
	if l == nil {
		return nil
	}
	return l.IsTransactionTax
}

func (l *LinkedTaxDetail) GetIsPrimaryTax() *bool {
	if l == nil {
		return nil
	}
	return l.IsPrimaryTax
}
