// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkedSubsidiaryInput struct {
	// Id to be displayed.
	DisplayID *string `json:"display_id,omitempty"`
	// The name of the resource.
	Name *string `json:"name,omitempty"`
}

func (l *LinkedSubsidiaryInput) GetDisplayID() *string {
	if l == nil {
		return nil
	}
	return l.DisplayID
}

func (l *LinkedSubsidiaryInput) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}
