// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// LinkedSupplier - The supplier this entity is linked to.
type LinkedSupplier struct {
	// The ID of the supplier this entity is linked to.
	ID *string `json:"id,omitempty"`
	// The display ID of the supplier.
	DisplayID *string `json:"display_id,omitempty"`
	// The display name of the supplier.
	DisplayName *string `json:"display_name,omitempty"`
	// The company name of the supplier.
	CompanyName *string  `json:"company_name,omitempty"`
	Address     *Address `json:"address,omitempty"`
}

func (l *LinkedSupplier) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LinkedSupplier) GetDisplayID() *string {
	if l == nil {
		return nil
	}
	return l.DisplayID
}

func (l *LinkedSupplier) GetDisplayName() *string {
	if l == nil {
		return nil
	}
	return l.DisplayName
}

func (l *LinkedSupplier) GetCompanyName() *string {
	if l == nil {
		return nil
	}
	return l.CompanyName
}

func (l *LinkedSupplier) GetAddress() *Address {
	if l == nil {
		return nil
	}
	return l.Address
}
