// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type PaymentInput struct {
	// Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
	Currency *Currency `json:"currency,omitempty"`
	// Currency Exchange Rate at the time entity was recorded/generated.
	CurrencyRate *float64 `json:"currency_rate,omitempty"`
	// The total amount of the transaction or record
	TotalAmount *float64 `json:"total_amount"`
	// Optional transaction reference message ie: Debit remittance detail.
	Reference *string `json:"reference,omitempty"`
	// Payment method used for the transaction, such as cash, credit card, bank transfer, or check
	PaymentMethod *string `json:"payment_method,omitempty"`
	// Optional reference message returned by payment method on processing
	PaymentMethodReference *string `json:"payment_method_reference,omitempty"`
	// A unique identifier for an object.
	PaymentMethodID *string `json:"payment_method_id,omitempty"`
	// Type of accounts receivable account.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	AccountsReceivableAccountType *string `json:"accounts_receivable_account_type,omitempty"`
	// Unique identifier for the account to allocate payment to.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	AccountsReceivableAccountID *string                   `json:"accounts_receivable_account_id,omitempty"`
	Account                     *LinkedLedgerAccountInput `json:"account,omitempty"`
	// The date of the transaction - YYYY:MM::DDThh:mm:ss.sTZD
	TransactionDate *time.Time `json:"transaction_date"`
	// The customer this entity is linked to.
	Customer *LinkedCustomerInput `json:"customer,omitempty"`
	// The supplier this entity is linked to.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Supplier *DeprecatedLinkedSupplierInput `json:"supplier,omitempty"`
	// The company ID the transaction belongs to
	CompanyID *string `json:"company_id,omitempty"`
	// Indicates if the transaction has been reconciled.
	Reconciled *bool `json:"reconciled,omitempty"`
	// Status of payment
	Status *PaymentStatus `json:"status,omitempty"`
	// Type of payment
	Type        *PaymentType      `json:"type,omitempty"`
	Allocations []AllocationInput `json:"allocations,omitempty"`
	// Note associated with the transaction
	Note *string `json:"note,omitempty"`
	// Number associated with the transaction
	Number *string `json:"number,omitempty"`
	// A list of linked tracking categories.
	TrackingCategories []*LinkedTrackingCategory `json:"tracking_categories,omitempty"`
	CustomFields       []CustomField             `json:"custom_fields,omitempty"`
	// A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.
	RowVersion *string `json:"row_version,omitempty"`
	// Id to be displayed.
	DisplayID *string `json:"display_id,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
}

func (p PaymentInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"total_amount", "transaction_date"}); err != nil {
		return err
	}
	return nil
}

func (p *PaymentInput) GetCurrency() *Currency {
	if p == nil {
		return nil
	}
	return p.Currency
}

func (p *PaymentInput) GetCurrencyRate() *float64 {
	if p == nil {
		return nil
	}
	return p.CurrencyRate
}

func (p *PaymentInput) GetTotalAmount() *float64 {
	if p == nil {
		return nil
	}
	return p.TotalAmount
}

func (p *PaymentInput) GetReference() *string {
	if p == nil {
		return nil
	}
	return p.Reference
}

func (p *PaymentInput) GetPaymentMethod() *string {
	if p == nil {
		return nil
	}
	return p.PaymentMethod
}

func (p *PaymentInput) GetPaymentMethodReference() *string {
	if p == nil {
		return nil
	}
	return p.PaymentMethodReference
}

func (p *PaymentInput) GetPaymentMethodID() *string {
	if p == nil {
		return nil
	}
	return p.PaymentMethodID
}

func (p *PaymentInput) GetAccountsReceivableAccountType() *string {
	if p == nil {
		return nil
	}
	return p.AccountsReceivableAccountType
}

func (p *PaymentInput) GetAccountsReceivableAccountID() *string {
	if p == nil {
		return nil
	}
	return p.AccountsReceivableAccountID
}

func (p *PaymentInput) GetAccount() *LinkedLedgerAccountInput {
	if p == nil {
		return nil
	}
	return p.Account
}

func (p *PaymentInput) GetTransactionDate() *time.Time {
	if p == nil {
		return nil
	}
	return p.TransactionDate
}

func (p *PaymentInput) GetCustomer() *LinkedCustomerInput {
	if p == nil {
		return nil
	}
	return p.Customer
}

func (p *PaymentInput) GetSupplier() *DeprecatedLinkedSupplierInput {
	if p == nil {
		return nil
	}
	return p.Supplier
}

func (p *PaymentInput) GetCompanyID() *string {
	if p == nil {
		return nil
	}
	return p.CompanyID
}

func (p *PaymentInput) GetReconciled() *bool {
	if p == nil {
		return nil
	}
	return p.Reconciled
}

func (p *PaymentInput) GetStatus() *PaymentStatus {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PaymentInput) GetType() *PaymentType {
	if p == nil {
		return nil
	}
	return p.Type
}

func (p *PaymentInput) GetAllocations() []AllocationInput {
	if p == nil {
		return nil
	}
	return p.Allocations
}

func (p *PaymentInput) GetNote() *string {
	if p == nil {
		return nil
	}
	return p.Note
}

func (p *PaymentInput) GetNumber() *string {
	if p == nil {
		return nil
	}
	return p.Number
}

func (p *PaymentInput) GetTrackingCategories() []*LinkedTrackingCategory {
	if p == nil {
		return nil
	}
	return p.TrackingCategories
}

func (p *PaymentInput) GetCustomFields() []CustomField {
	if p == nil {
		return nil
	}
	return p.CustomFields
}

func (p *PaymentInput) GetRowVersion() *string {
	if p == nil {
		return nil
	}
	return p.RowVersion
}

func (p *PaymentInput) GetDisplayID() *string {
	if p == nil {
		return nil
	}
	return p.DisplayID
}

func (p *PaymentInput) GetPassThrough() []PassThroughBody {
	if p == nil {
		return nil
	}
	return p.PassThrough
}
