// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type PaymentsFilterType string

const (
	PaymentsFilterTypeAccountsReceivable            PaymentsFilterType = "accounts_receivable"
	PaymentsFilterTypeAccountsPayable               PaymentsFilterType = "accounts_payable"
	PaymentsFilterTypeAccountsReceivableCredit      PaymentsFilterType = "accounts_receivable_credit"
	PaymentsFilterTypeAccountsPayableCredit         PaymentsFilterType = "accounts_payable_credit"
	PaymentsFilterTypeAccountsReceivableOverpayment PaymentsFilterType = "accounts_receivable_overpayment"
	PaymentsFilterTypeAccountsPayableOverpayment    PaymentsFilterType = "accounts_payable_overpayment"
	PaymentsFilterTypeAccountsReceivablePrepayment  PaymentsFilterType = "accounts_receivable_prepayment"
	PaymentsFilterTypeAccountsPayablePrepayment     PaymentsFilterType = "accounts_payable_prepayment"
)

func (e PaymentsFilterType) ToPointer() *PaymentsFilterType {
	return &e
}
func (e *PaymentsFilterType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "accounts_receivable":
		fallthrough
	case "accounts_payable":
		fallthrough
	case "accounts_receivable_credit":
		fallthrough
	case "accounts_payable_credit":
		fallthrough
	case "accounts_receivable_overpayment":
		fallthrough
	case "accounts_payable_overpayment":
		fallthrough
	case "accounts_receivable_prepayment":
		fallthrough
	case "accounts_payable_prepayment":
		*e = PaymentsFilterType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentsFilterType: %v", v)
	}
}

type PaymentsFilter struct {
	UpdatedSince *time.Time `queryParam:"name=updated_since"`
	InvoiceID    *string    `queryParam:"name=invoice_id"`
	SupplierID   *string    `queryParam:"name=supplier_id"`
	// Filter by customer id
	CustomerID *string             `queryParam:"name=customer_id"`
	Type       *PaymentsFilterType `queryParam:"name=type"`
}

func (p PaymentsFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentsFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentsFilter) GetUpdatedSince() *time.Time {
	if p == nil {
		return nil
	}
	return p.UpdatedSince
}

func (p *PaymentsFilter) GetInvoiceID() *string {
	if p == nil {
		return nil
	}
	return p.InvoiceID
}

func (p *PaymentsFilter) GetSupplierID() *string {
	if p == nil {
		return nil
	}
	return p.SupplierID
}

func (p *PaymentsFilter) GetCustomerID() *string {
	if p == nil {
		return nil
	}
	return p.CustomerID
}

func (p *PaymentsFilter) GetType() *PaymentsFilterType {
	if p == nil {
		return nil
	}
	return p.Type
}
