// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProfitAndLossFilterAccountingMethod - The accounting method used for the report: cash or accrual.
type ProfitAndLossFilterAccountingMethod string

const (
	ProfitAndLossFilterAccountingMethodCash    ProfitAndLossFilterAccountingMethod = "cash"
	ProfitAndLossFilterAccountingMethodAccrual ProfitAndLossFilterAccountingMethod = "accrual"
)

func (e ProfitAndLossFilterAccountingMethod) ToPointer() *ProfitAndLossFilterAccountingMethod {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProfitAndLossFilterAccountingMethod) IsExact() bool {
	if e != nil {
		switch *e {
		case "cash", "accrual":
			return true
		}
	}
	return false
}

type ProfitAndLossFilter struct {
	// Filter by customer id
	CustomerID *string `queryParam:"name=customer_id"`
	// Filter by start date. If start date is given, end date is required.
	StartDate *string `queryParam:"name=start_date"`
	// Filter by end date. If end date is given, start date is required.
	EndDate *string `queryParam:"name=end_date"`
	// Filter by location id
	LocationID *string `queryParam:"name=location_id"`
	// The accounting method used for the report: cash or accrual.
	AccountingMethod *ProfitAndLossFilterAccountingMethod `queryParam:"name=accounting_method"`
}

func (p *ProfitAndLossFilter) GetCustomerID() *string {
	if p == nil {
		return nil
	}
	return p.CustomerID
}

func (p *ProfitAndLossFilter) GetStartDate() *string {
	if p == nil {
		return nil
	}
	return p.StartDate
}

func (p *ProfitAndLossFilter) GetEndDate() *string {
	if p == nil {
		return nil
	}
	return p.EndDate
}

func (p *ProfitAndLossFilter) GetLocationID() *string {
	if p == nil {
		return nil
	}
	return p.LocationID
}

func (p *ProfitAndLossFilter) GetAccountingMethod() *ProfitAndLossFilterAccountingMethod {
	if p == nil {
		return nil
	}
	return p.AccountingMethod
}
