// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type QuotesFilter struct {
	UpdatedSince *time.Time `queryParam:"name=updated_since"`
	CreatedSince *time.Time `queryParam:"name=created_since"`
	// Quote number to search for
	Number *string `queryParam:"name=number"`
}

func (q QuotesFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuotesFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QuotesFilter) GetUpdatedSince() *time.Time {
	if q == nil {
		return nil
	}
	return q.UpdatedSince
}

func (q *QuotesFilter) GetCreatedSince() *time.Time {
	if q == nil {
		return nil
	}
	return q.CreatedSince
}

func (q *QuotesFilter) GetNumber() *string {
	if q == nil {
		return nil
	}
	return q.Number
}
