// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type Refund struct {
	// Unique identifier representing the refund
	ID string `json:"id"`
	// Reference number for the refund.
	Number *string `json:"number,omitempty"`
	// The customer this entity is linked to.
	Customer *LinkedCustomer `json:"customer,omitempty"`
	// The company ID the transaction belongs to
	CompanyID *string `json:"company_id,omitempty"`
	// Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
	Currency *Currency `json:"currency,omitempty"`
	// Currency Exchange Rate at the time entity was recorded/generated.
	CurrencyRate *float64 `json:"currency_rate,omitempty"`
	// Amounts are including tax
	TaxInclusive *bool `json:"tax_inclusive,omitempty"`
	// Subtotal amount, normally before tax.
	SubTotal *float64 `json:"sub_total,omitempty"`
	// The total amount of the transaction or record
	TotalAmount *float64 `json:"total_amount"`
	// Total tax amount applied to this transaction.
	TotalTax *float64 `json:"total_tax,omitempty"`
	// The date of the refund - YYYY-MM-DDThh:mm:ss.sTZD
	RefundDate *time.Time `json:"refund_date,omitempty"`
	// Status of refund. Maps to: QBO (limited status), NetSuite CashRefund status, Sage Intacct state (draft/posted/voided), Zoho Books vis_state.
	Status *RefundStatus `json:"status,omitempty"`
	// Type of refund. `refund_receipt` for itemized refunds with product/service lines and payment (QBO RefundReceipt, NetSuite CashRefund). `cash_refund` for cash-out refunds with GL distribution or allocations (Sage Intacct). `credit_note_refund` for refunds applied against a credit note (Zoho Books).
	Type *RefundType `json:"type,omitempty"`
	// Payment method used for the transaction, such as cash, credit card, bank transfer, or check
	PaymentMethod *string `json:"payment_method,omitempty"`
	// Optional reference message returned by payment method on processing
	PaymentMethodReference *string `json:"payment_method_reference,omitempty"`
	// A unique identifier for an object.
	PaymentMethodID *string              `json:"payment_method_id,omitempty"`
	Account         *LinkedLedgerAccount `json:"account,omitempty"`
	// Line items for itemized refunds (type: refund_receipt). Used when the refund includes product/service details with quantities and pricing. Supported by QBO RefundReceipt and NetSuite CashRefund.
	LineItems []InvoiceLineItem `json:"line_items,omitempty"`
	// Allocations linking refund to existing documents (invoices, credit notes, overpayments). Used for credit_note_refund and cash_refund types where the refund is applied against prior transactions. Supported by Sage Intacct and Zoho Books.
	Allocations []Allocation `json:"allocations,omitempty"`
	// Applicable tax id/code override if tax is not supplied on a line item basis.
	TaxCode *string `json:"tax_code,omitempty"`
	// Discount percentage applied to this refund.
	DiscountPercentage *float64 `json:"discount_percentage,omitempty"`
	// Discount amount applied to this refund.
	DiscountAmount *float64 `json:"discount_amount,omitempty"`
	// Optional note to be associated with the refund.
	Note *string `json:"note,omitempty"`
	// Customer memo
	CustomerMemo *string `json:"customer_memo,omitempty"`
	// Optional reference message for the refund.
	Reference       *string           `json:"reference,omitempty"`
	BillingAddress  *Address          `json:"billing_address,omitempty"`
	ShippingAddress *Address          `json:"shipping_address,omitempty"`
	Department      *LinkedDepartment `json:"department,omitempty"`
	Location        *LinkedLocation   `json:"location,omitempty"`
	// A list of linked tracking categories.
	TrackingCategories []*LinkedTrackingCategory `json:"tracking_categories,omitempty"`
	// When custom mappings are configured on the resource, the result is included here.
	CustomMappings map[string]any `json:"custom_mappings,omitempty"`
	CustomFields   []CustomField  `json:"custom_fields,omitempty"`
	// A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.
	RowVersion *string `json:"row_version,omitempty"`
	// The user who last updated the object.
	UpdatedBy *string `json:"updated_by,omitempty"`
	// The user who created the object.
	CreatedBy *string `json:"created_by,omitempty"`
	// The date and time when the object was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// The date and time when the object was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
}

func (r Refund) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Refund) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Refund) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *Refund) GetNumber() *string {
	if r == nil {
		return nil
	}
	return r.Number
}

func (r *Refund) GetCustomer() *LinkedCustomer {
	if r == nil {
		return nil
	}
	return r.Customer
}

func (r *Refund) GetCompanyID() *string {
	if r == nil {
		return nil
	}
	return r.CompanyID
}

func (r *Refund) GetCurrency() *Currency {
	if r == nil {
		return nil
	}
	return r.Currency
}

func (r *Refund) GetCurrencyRate() *float64 {
	if r == nil {
		return nil
	}
	return r.CurrencyRate
}

func (r *Refund) GetTaxInclusive() *bool {
	if r == nil {
		return nil
	}
	return r.TaxInclusive
}

func (r *Refund) GetSubTotal() *float64 {
	if r == nil {
		return nil
	}
	return r.SubTotal
}

func (r *Refund) GetTotalAmount() *float64 {
	if r == nil {
		return nil
	}
	return r.TotalAmount
}

func (r *Refund) GetTotalTax() *float64 {
	if r == nil {
		return nil
	}
	return r.TotalTax
}

func (r *Refund) GetRefundDate() *time.Time {
	if r == nil {
		return nil
	}
	return r.RefundDate
}

func (r *Refund) GetStatus() *RefundStatus {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *Refund) GetType() *RefundType {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *Refund) GetPaymentMethod() *string {
	if r == nil {
		return nil
	}
	return r.PaymentMethod
}

func (r *Refund) GetPaymentMethodReference() *string {
	if r == nil {
		return nil
	}
	return r.PaymentMethodReference
}

func (r *Refund) GetPaymentMethodID() *string {
	if r == nil {
		return nil
	}
	return r.PaymentMethodID
}

func (r *Refund) GetAccount() *LinkedLedgerAccount {
	if r == nil {
		return nil
	}
	return r.Account
}

func (r *Refund) GetLineItems() []InvoiceLineItem {
	if r == nil {
		return nil
	}
	return r.LineItems
}

func (r *Refund) GetAllocations() []Allocation {
	if r == nil {
		return nil
	}
	return r.Allocations
}

func (r *Refund) GetTaxCode() *string {
	if r == nil {
		return nil
	}
	return r.TaxCode
}

func (r *Refund) GetDiscountPercentage() *float64 {
	if r == nil {
		return nil
	}
	return r.DiscountPercentage
}

func (r *Refund) GetDiscountAmount() *float64 {
	if r == nil {
		return nil
	}
	return r.DiscountAmount
}

func (r *Refund) GetNote() *string {
	if r == nil {
		return nil
	}
	return r.Note
}

func (r *Refund) GetCustomerMemo() *string {
	if r == nil {
		return nil
	}
	return r.CustomerMemo
}

func (r *Refund) GetReference() *string {
	if r == nil {
		return nil
	}
	return r.Reference
}

func (r *Refund) GetBillingAddress() *Address {
	if r == nil {
		return nil
	}
	return r.BillingAddress
}

func (r *Refund) GetShippingAddress() *Address {
	if r == nil {
		return nil
	}
	return r.ShippingAddress
}

func (r *Refund) GetDepartment() *LinkedDepartment {
	if r == nil {
		return nil
	}
	return r.Department
}

func (r *Refund) GetLocation() *LinkedLocation {
	if r == nil {
		return nil
	}
	return r.Location
}

func (r *Refund) GetTrackingCategories() []*LinkedTrackingCategory {
	if r == nil {
		return nil
	}
	return r.TrackingCategories
}

func (r *Refund) GetCustomMappings() map[string]any {
	if r == nil {
		return nil
	}
	return r.CustomMappings
}

func (r *Refund) GetCustomFields() []CustomField {
	if r == nil {
		return nil
	}
	return r.CustomFields
}

func (r *Refund) GetRowVersion() *string {
	if r == nil {
		return nil
	}
	return r.RowVersion
}

func (r *Refund) GetUpdatedBy() *string {
	if r == nil {
		return nil
	}
	return r.UpdatedBy
}

func (r *Refund) GetCreatedBy() *string {
	if r == nil {
		return nil
	}
	return r.CreatedBy
}

func (r *Refund) GetUpdatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.UpdatedAt
}

func (r *Refund) GetCreatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *Refund) GetPassThrough() []PassThroughBody {
	if r == nil {
		return nil
	}
	return r.PassThrough
}
