// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type SalesReceiptsFilter struct {
	UpdatedSince *time.Time `queryParam:"name=updated_since"`
	// Filter by customer id
	CustomerID *string `queryParam:"name=customer_id"`
}

func (s SalesReceiptsFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SalesReceiptsFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SalesReceiptsFilter) GetUpdatedSince() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedSince
}

func (s *SalesReceiptsFilter) GetCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.CustomerID
}
