// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type SalesOrdersFilter struct {
	UpdatedSince *time.Time `queryParam:"name=updated_since"`
	CreatedSince *time.Time `queryParam:"name=created_since"`
	// Sales order number to search for
	Number *string `queryParam:"name=number"`
	// Filter by customer id
	CustomerID *string `queryParam:"name=customer_id"`
	// Filter by the subsidiary (legal entity) the record belongs to. Only honored on connectors that support multi-entity scoping (e.g. NetSuite OneWorld); ignored elsewhere.
	SubsidiaryID *string `queryParam:"name=subsidiary_id"`
}

func (s SalesOrdersFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SalesOrdersFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SalesOrdersFilter) GetUpdatedSince() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedSince
}

func (s *SalesOrdersFilter) GetCreatedSince() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedSince
}

func (s *SalesOrdersFilter) GetNumber() *string {
	if s == nil {
		return nil
	}
	return s.Number
}

func (s *SalesOrdersFilter) GetCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.CustomerID
}

func (s *SalesOrdersFilter) GetSubsidiaryID() *string {
	if s == nil {
		return nil
	}
	return s.SubsidiaryID
}
