// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/apideck-libraries/sdk-go/internal/utils"
)

type FiveType string

const (
	FiveTypeStr     FiveType = "str"
	FiveTypeInteger FiveType = "integer"
	FiveTypeNumber  FiveType = "number"
)

type Five struct {
	Str     *string  `queryParam:"inline" union:"member"`
	Integer *int64   `queryParam:"inline" union:"member"`
	Number  *float64 `queryParam:"inline" union:"member"`

	Type FiveType
}

func CreateFiveStr(str string) Five {
	typ := FiveTypeStr

	return Five{
		Str:  &str,
		Type: typ,
	}
}

func CreateFiveInteger(integer int64) Five {
	typ := FiveTypeInteger

	return Five{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateFiveNumber(number float64) Five {
	typ := FiveTypeNumber

	return Five{
		Number: &number,
		Type:   typ,
	}
}

func (u *Five) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = FiveTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = FiveTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = FiveTypeNumber
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Five", string(data))
}

func (u Five) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type Five: all fields are null")
}

type ValueType string

const (
	ValueTypeStr      ValueType = "str"
	ValueTypeInteger  ValueType = "integer"
	ValueTypeNumber   ValueType = "number"
	ValueTypeBoolean  ValueType = "boolean"
	ValueTypeArrayOf5 ValueType = "arrayOf5"
)

type Value struct {
	Str      *string  `queryParam:"inline" union:"member"`
	Integer  *int64   `queryParam:"inline" union:"member"`
	Number   *float64 `queryParam:"inline" union:"member"`
	Boolean  *bool    `queryParam:"inline" union:"member"`
	ArrayOf5 []Five   `queryParam:"inline" union:"member"`

	Type ValueType
}

func CreateValueStr(str string) Value {
	typ := ValueTypeStr

	return Value{
		Str:  &str,
		Type: typ,
	}
}

func CreateValueInteger(integer int64) Value {
	typ := ValueTypeInteger

	return Value{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateValueNumber(number float64) Value {
	typ := ValueTypeNumber

	return Value{
		Number: &number,
		Type:   typ,
	}
}

func CreateValueBoolean(boolean bool) Value {
	typ := ValueTypeBoolean

	return Value{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateValueArrayOf5(arrayOf5 []Five) Value {
	typ := ValueTypeArrayOf5

	return Value{
		ArrayOf5: arrayOf5,
		Type:     typ,
	}
}

func (u *Value) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = ValueTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = ValueTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = ValueTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = ValueTypeBoolean
		return nil
	}

	var arrayOf5 []Five = []Five{}
	if err := utils.UnmarshalJSON(data, &arrayOf5, "", true, nil); err == nil {
		u.ArrayOf5 = arrayOf5
		u.Type = ValueTypeArrayOf5
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value", string(data))
}

func (u Value) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.ArrayOf5 != nil {
		return utils.MarshalJSON(u.ArrayOf5, "", true)
	}

	return nil, errors.New("could not marshal union type Value: all fields are null")
}

type OptionType string

const (
	OptionTypeSimple OptionType = "simple"
)

func (e OptionType) ToPointer() *OptionType {
	return &e
}
func (e *OptionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "simple":
		*e = OptionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OptionType: %v", v)
	}
}

type SimpleFormFieldOption struct {
	Label      string     `json:"label"`
	Value      *Value     `json:"value,omitempty"`
	OptionType OptionType `json:"option_type"`
}

func (s SimpleFormFieldOption) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimpleFormFieldOption) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"label", "option_type"}); err != nil {
		return err
	}
	return nil
}

func (s *SimpleFormFieldOption) GetLabel() string {
	if s == nil {
		return ""
	}
	return s.Label
}

func (s *SimpleFormFieldOption) GetValue() *Value {
	if s == nil {
		return nil
	}
	return s.Value
}

func (s *SimpleFormFieldOption) GetOptionType() OptionType {
	if s == nil {
		return OptionType("")
	}
	return s.OptionType
}
