// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

// TrackingCategoryStatus - Based on the status some functionality is enabled or disabled.
type TrackingCategoryStatus string

const (
	TrackingCategoryStatusActive   TrackingCategoryStatus = "active"
	TrackingCategoryStatusInactive TrackingCategoryStatus = "inactive"
)

func (e TrackingCategoryStatus) ToPointer() *TrackingCategoryStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TrackingCategoryStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "inactive":
			return true
		}
	}
	return false
}

type TrackingCategorySubsidiaries struct {
	// The ID of the subsidiary.
	ID *string `json:"id,omitempty"`
}

func (t *TrackingCategorySubsidiaries) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

type TrackingCategory struct {
	// A unique identifier for an object.
	ID *string `json:"id,omitempty"`
	// A unique identifier for an object.
	ParentID *string `json:"parent_id,omitempty"`
	// The name of the parent tracking category.
	ParentName *string `json:"parent_name,omitempty"`
	// The name of the tracking category.
	Name *string `json:"name,omitempty"`
	// The code of the tracking category.
	Code *string `json:"code,omitempty"`
	// Based on the status some functionality is enabled or disabled.
	Status *TrackingCategoryStatus `json:"status,omitempty"`
	// When custom mappings are configured on the resource, the result is included here.
	CustomMappings map[string]any `json:"custom_mappings,omitempty"`
	// A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.
	RowVersion *string `json:"row_version,omitempty"`
	// The user who last updated the object.
	UpdatedBy *string `json:"updated_by,omitempty"`
	// The user who created the object.
	CreatedBy *string `json:"created_by,omitempty"`
	// The date and time when the object was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// The date and time when the object was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
	// The subsidiaries the account belongs to.
	Subsidiaries []TrackingCategorySubsidiaries `json:"subsidiaries,omitempty"`
}

func (t TrackingCategory) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TrackingCategory) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TrackingCategory) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TrackingCategory) GetParentID() *string {
	if t == nil {
		return nil
	}
	return t.ParentID
}

func (t *TrackingCategory) GetParentName() *string {
	if t == nil {
		return nil
	}
	return t.ParentName
}

func (t *TrackingCategory) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TrackingCategory) GetCode() *string {
	if t == nil {
		return nil
	}
	return t.Code
}

func (t *TrackingCategory) GetStatus() *TrackingCategoryStatus {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TrackingCategory) GetCustomMappings() map[string]any {
	if t == nil {
		return nil
	}
	return t.CustomMappings
}

func (t *TrackingCategory) GetRowVersion() *string {
	if t == nil {
		return nil
	}
	return t.RowVersion
}

func (t *TrackingCategory) GetUpdatedBy() *string {
	if t == nil {
		return nil
	}
	return t.UpdatedBy
}

func (t *TrackingCategory) GetCreatedBy() *string {
	if t == nil {
		return nil
	}
	return t.CreatedBy
}

func (t *TrackingCategory) GetUpdatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.UpdatedAt
}

func (t *TrackingCategory) GetCreatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.CreatedAt
}

func (t *TrackingCategory) GetPassThrough() []PassThroughBody {
	if t == nil {
		return nil
	}
	return t.PassThrough
}

func (t *TrackingCategory) GetSubsidiaries() []TrackingCategorySubsidiaries {
	if t == nil {
		return nil
	}
	return t.Subsidiaries
}

type TrackingCategoryInput struct {
	// A unique identifier for an object.
	ParentID *string `json:"parent_id,omitempty"`
	// The name of the parent tracking category.
	ParentName *string `json:"parent_name,omitempty"`
	// The name of the tracking category.
	Name *string `json:"name,omitempty"`
	// The code of the tracking category.
	Code *string `json:"code,omitempty"`
	// Based on the status some functionality is enabled or disabled.
	Status *TrackingCategoryStatus `json:"status,omitempty"`
	// A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.
	RowVersion *string `json:"row_version,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
	// The subsidiaries the account belongs to.
	Subsidiaries []TrackingCategorySubsidiaries `json:"subsidiaries,omitempty"`
}

func (t *TrackingCategoryInput) GetParentID() *string {
	if t == nil {
		return nil
	}
	return t.ParentID
}

func (t *TrackingCategoryInput) GetParentName() *string {
	if t == nil {
		return nil
	}
	return t.ParentName
}

func (t *TrackingCategoryInput) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TrackingCategoryInput) GetCode() *string {
	if t == nil {
		return nil
	}
	return t.Code
}

func (t *TrackingCategoryInput) GetStatus() *TrackingCategoryStatus {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TrackingCategoryInput) GetRowVersion() *string {
	if t == nil {
		return nil
	}
	return t.RowVersion
}

func (t *TrackingCategoryInput) GetPassThrough() []PassThroughBody {
	if t == nil {
		return nil
	}
	return t.PassThrough
}

func (t *TrackingCategoryInput) GetSubsidiaries() []TrackingCategorySubsidiaries {
	if t == nil {
		return nil
	}
	return t.Subsidiaries
}
