// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateSalesOrderResponse - Sales Orders
type UpdateSalesOrderResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string `json:"operation"`
	// A object containing a unique identifier for the resource that was created, updated, or deleted.
	Data UnifiedID `json:"data"`
}

func (u *UpdateSalesOrderResponse) GetStatusCode() int64 {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateSalesOrderResponse) GetStatus() string {
	if u == nil {
		return ""
	}
	return u.Status
}

func (u *UpdateSalesOrderResponse) GetService() string {
	if u == nil {
		return ""
	}
	return u.Service
}

func (u *UpdateSalesOrderResponse) GetResource() string {
	if u == nil {
		return ""
	}
	return u.Resource
}

func (u *UpdateSalesOrderResponse) GetOperation() string {
	if u == nil {
		return ""
	}
	return u.Operation
}

func (u *UpdateSalesOrderResponse) GetData() UnifiedID {
	if u == nil {
		return UnifiedID{}
	}
	return u.Data
}
