// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateContactResponse - Contact updated
type UpdateContactResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string `json:"operation"`
	// A object containing a unique identifier for the resource that was created, updated, or deleted.
	Data UnifiedID `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (u *UpdateContactResponse) GetStatusCode() int64 {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateContactResponse) GetStatus() string {
	if u == nil {
		return ""
	}
	return u.Status
}

func (u *UpdateContactResponse) GetService() string {
	if u == nil {
		return ""
	}
	return u.Service
}

func (u *UpdateContactResponse) GetResource() string {
	if u == nil {
		return ""
	}
	return u.Resource
}

func (u *UpdateContactResponse) GetOperation() string {
	if u == nil {
		return ""
	}
	return u.Operation
}

func (u *UpdateContactResponse) GetData() UnifiedID {
	if u == nil {
		return UnifiedID{}
	}
	return u.Data
}

func (u *UpdateContactResponse) GetRaw() map[string]any {
	if u == nil {
		return nil
	}
	return u.Raw
}
