// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateConsumerRequest struct {
	// The metadata of the consumer. This is used to display the consumer in the sidebar. This is optional, but recommended.
	Metadata *ConsumerMetadata `json:"metadata,omitempty"`
}

func (u *UpdateConsumerRequest) GetMetadata() *ConsumerMetadata {
	if u == nil {
		return nil
	}
	return u.Metadata
}
