// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/apideck-libraries/sdk-go/internal/utils"
	"time"
)

type UploadSession struct {
	// A unique identifier for an object.
	ID *string `json:"id,omitempty"`
	// Indicates if the upload session was completed successfully.
	Success *bool `json:"success,omitempty"`
	// Size in bytes of each part of the file that you will upload. Uploaded parts need to be this size for the upload to be successful.
	PartSize *float64 `json:"part_size,omitempty"`
	// Indicates if parts of the file can uploaded in parallel.
	ParallelUploadSupported *bool `json:"parallel_upload_supported,omitempty"`
	// The range of bytes that was successfully uploaded.
	UploadedByteRange *string    `json:"uploaded_byte_range,omitempty"`
	ExpiresAt         *time.Time `json:"expires_at,omitempty"`
}

func (u UploadSession) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadSession) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadSession) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UploadSession) GetSuccess() *bool {
	if u == nil {
		return nil
	}
	return u.Success
}

func (u *UploadSession) GetPartSize() *float64 {
	if u == nil {
		return nil
	}
	return u.PartSize
}

func (u *UploadSession) GetParallelUploadSupported() *bool {
	if u == nil {
		return nil
	}
	return u.ParallelUploadSupported
}

func (u *UploadSession) GetUploadedByteRange() *string {
	if u == nil {
		return nil
	}
	return u.UploadedByteRange
}

func (u *UploadSession) GetExpiresAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.ExpiresAt
}
